// Code generated by protoc-gen-go. DO NOT EDIT.
// source: codec.proto

package test

import (
	fmt "fmt"
	_ "github.com/galaxyobe/protoc-gen-redis/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type JsonStringStorageType_Enum int32

const (
	JsonStringStorageType_E1 JsonStringStorageType_Enum = 0
	JsonStringStorageType_E2 JsonStringStorageType_Enum = 1
	JsonStringStorageType_E3 JsonStringStorageType_Enum = 2
)

var JsonStringStorageType_Enum_name = map[int32]string{
	0: "E1",
	1: "E2",
	2: "E3",
}

var JsonStringStorageType_Enum_value = map[string]int32{
	"E1": 0,
	"E2": 1,
	"E3": 2,
}

func (x JsonStringStorageType_Enum) String() string {
	return proto.EnumName(JsonStringStorageType_Enum_name, int32(x))
}

func (JsonStringStorageType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9610d574777ab505, []int{0, 0}
}

type JsonHashStorageType_Enum int32

const (
	JsonHashStorageType_E1 JsonHashStorageType_Enum = 0
	JsonHashStorageType_E2 JsonHashStorageType_Enum = 1
	JsonHashStorageType_E3 JsonHashStorageType_Enum = 2
)

var JsonHashStorageType_Enum_name = map[int32]string{
	0: "E1",
	1: "E2",
	2: "E3",
}

var JsonHashStorageType_Enum_value = map[string]int32{
	"E1": 0,
	"E2": 1,
	"E3": 2,
}

func (x JsonHashStorageType_Enum) String() string {
	return proto.EnumName(JsonHashStorageType_Enum_name, int32(x))
}

func (JsonHashStorageType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_9610d574777ab505, []int{1, 0}
}

type JsonStringStorageType struct {
	SomeString            string                     `protobuf:"bytes,1,opt,name=some_string,json=someString,proto3" json:"some_string,omitempty"`
	SomeBool              bool                       `protobuf:"varint,2,opt,name=some_bool,json=someBool,proto3" json:"some_bool,omitempty"`
	SomeInt32             int32                      `protobuf:"varint,3,opt,name=some_int32,json=someInt32,proto3" json:"some_int32,omitempty"`
	SomeUint32            uint32                     `protobuf:"varint,4,opt,name=some_uint32,json=someUint32,proto3" json:"some_uint32,omitempty"`
	SomeInt64             int64                      `protobuf:"varint,5,opt,name=some_int64,json=someInt64,proto3" json:"some_int64,omitempty"`
	SomeUint64            uint64                     `protobuf:"varint,6,opt,name=some_uint64,json=someUint64,proto3" json:"some_uint64,omitempty"`
	SomeFloat             float32                    `protobuf:"fixed32,7,opt,name=some_float,json=someFloat,proto3" json:"some_float,omitempty"`
	SomeEnum              JsonStringStorageType_Enum `protobuf:"varint,8,opt,name=some_enum,json=someEnum,proto3,enum=test.JsonStringStorageType_Enum" json:"some_enum,omitempty"`
	Timestamp             *timestamp.Timestamp       `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	JsonStringStorageType *JsonStringStorageType     `protobuf:"bytes,10,opt,name=JsonStringStorageType,proto3" json:"JsonStringStorageType,omitempty"`
	SomeMessages          []*JsonStringStorageType   `protobuf:"bytes,11,rep,name=some_messages,json=someMessages,proto3" json:"some_messages,omitempty"`
	Timestamps            []*timestamp.Timestamp     `protobuf:"bytes,12,rep,name=timestamps,proto3" json:"timestamps,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}                   `json:"-"`
	XXX_unrecognized      []byte                     `json:"-"`
	XXX_sizecache         int32                      `json:"-"`
}

func (m *JsonStringStorageType) Reset()         { *m = JsonStringStorageType{} }
func (m *JsonStringStorageType) String() string { return proto.CompactTextString(m) }
func (*JsonStringStorageType) ProtoMessage()    {}
func (*JsonStringStorageType) Descriptor() ([]byte, []int) {
	return fileDescriptor_9610d574777ab505, []int{0}
}

func (m *JsonStringStorageType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JsonStringStorageType.Unmarshal(m, b)
}
func (m *JsonStringStorageType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JsonStringStorageType.Marshal(b, m, deterministic)
}
func (m *JsonStringStorageType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JsonStringStorageType.Merge(m, src)
}
func (m *JsonStringStorageType) XXX_Size() int {
	return xxx_messageInfo_JsonStringStorageType.Size(m)
}
func (m *JsonStringStorageType) XXX_DiscardUnknown() {
	xxx_messageInfo_JsonStringStorageType.DiscardUnknown(m)
}

var xxx_messageInfo_JsonStringStorageType proto.InternalMessageInfo

func (m *JsonStringStorageType) GetSomeString() string {
	if m != nil {
		return m.SomeString
	}
	return ""
}

func (m *JsonStringStorageType) GetSomeBool() bool {
	if m != nil {
		return m.SomeBool
	}
	return false
}

func (m *JsonStringStorageType) GetSomeInt32() int32 {
	if m != nil {
		return m.SomeInt32
	}
	return 0
}

func (m *JsonStringStorageType) GetSomeUint32() uint32 {
	if m != nil {
		return m.SomeUint32
	}
	return 0
}

func (m *JsonStringStorageType) GetSomeInt64() int64 {
	if m != nil {
		return m.SomeInt64
	}
	return 0
}

func (m *JsonStringStorageType) GetSomeUint64() uint64 {
	if m != nil {
		return m.SomeUint64
	}
	return 0
}

func (m *JsonStringStorageType) GetSomeFloat() float32 {
	if m != nil {
		return m.SomeFloat
	}
	return 0
}

func (m *JsonStringStorageType) GetSomeEnum() JsonStringStorageType_Enum {
	if m != nil {
		return m.SomeEnum
	}
	return JsonStringStorageType_E1
}

func (m *JsonStringStorageType) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *JsonStringStorageType) GetJsonStringStorageType() *JsonStringStorageType {
	if m != nil {
		return m.JsonStringStorageType
	}
	return nil
}

func (m *JsonStringStorageType) GetSomeMessages() []*JsonStringStorageType {
	if m != nil {
		return m.SomeMessages
	}
	return nil
}

func (m *JsonStringStorageType) GetTimestamps() []*timestamp.Timestamp {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

type JsonHashStorageType struct {
	SomeString           string                   `protobuf:"bytes,1,opt,name=some_string,json=someString,proto3" json:"some_string,omitempty"`
	SomeBool             bool                     `protobuf:"varint,2,opt,name=some_bool,json=someBool,proto3" json:"some_bool,omitempty"`
	SomeInt32            int32                    `protobuf:"varint,3,opt,name=some_int32,json=someInt32,proto3" json:"some_int32,omitempty"`
	SomeUint32           uint32                   `protobuf:"varint,4,opt,name=some_uint32,json=someUint32,proto3" json:"some_uint32,omitempty"`
	SomeInt64            int64                    `protobuf:"varint,5,opt,name=some_int64,json=someInt64,proto3" json:"some_int64,omitempty"`
	SomeUint64           uint64                   `protobuf:"varint,6,opt,name=some_uint64,json=someUint64,proto3" json:"some_uint64,omitempty"`
	SomeFloat            float32                  `protobuf:"fixed32,7,opt,name=some_float,json=someFloat,proto3" json:"some_float,omitempty"`
	SomeEnum             JsonHashStorageType_Enum `protobuf:"varint,8,opt,name=some_enum,json=someEnum,proto3,enum=test.JsonHashStorageType_Enum" json:"some_enum,omitempty"`
	Timestamp            *timestamp.Timestamp     `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	JsonHashStorageType  *JsonHashStorageType     `protobuf:"bytes,10,opt,name=JsonHashStorageType,proto3" json:"JsonHashStorageType,omitempty"`
	SomeMessages         []*JsonHashStorageType   `protobuf:"bytes,11,rep,name=some_messages,json=someMessages,proto3" json:"some_messages,omitempty"`
	Timestamps           []*timestamp.Timestamp   `protobuf:"bytes,12,rep,name=timestamps,proto3" json:"timestamps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                 `json:"-"`
	XXX_unrecognized     []byte                   `json:"-"`
	XXX_sizecache        int32                    `json:"-"`
}

func (m *JsonHashStorageType) Reset()         { *m = JsonHashStorageType{} }
func (m *JsonHashStorageType) String() string { return proto.CompactTextString(m) }
func (*JsonHashStorageType) ProtoMessage()    {}
func (*JsonHashStorageType) Descriptor() ([]byte, []int) {
	return fileDescriptor_9610d574777ab505, []int{1}
}

func (m *JsonHashStorageType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_JsonHashStorageType.Unmarshal(m, b)
}
func (m *JsonHashStorageType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_JsonHashStorageType.Marshal(b, m, deterministic)
}
func (m *JsonHashStorageType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_JsonHashStorageType.Merge(m, src)
}
func (m *JsonHashStorageType) XXX_Size() int {
	return xxx_messageInfo_JsonHashStorageType.Size(m)
}
func (m *JsonHashStorageType) XXX_DiscardUnknown() {
	xxx_messageInfo_JsonHashStorageType.DiscardUnknown(m)
}

var xxx_messageInfo_JsonHashStorageType proto.InternalMessageInfo

func (m *JsonHashStorageType) GetSomeString() string {
	if m != nil {
		return m.SomeString
	}
	return ""
}

func (m *JsonHashStorageType) GetSomeBool() bool {
	if m != nil {
		return m.SomeBool
	}
	return false
}

func (m *JsonHashStorageType) GetSomeInt32() int32 {
	if m != nil {
		return m.SomeInt32
	}
	return 0
}

func (m *JsonHashStorageType) GetSomeUint32() uint32 {
	if m != nil {
		return m.SomeUint32
	}
	return 0
}

func (m *JsonHashStorageType) GetSomeInt64() int64 {
	if m != nil {
		return m.SomeInt64
	}
	return 0
}

func (m *JsonHashStorageType) GetSomeUint64() uint64 {
	if m != nil {
		return m.SomeUint64
	}
	return 0
}

func (m *JsonHashStorageType) GetSomeFloat() float32 {
	if m != nil {
		return m.SomeFloat
	}
	return 0
}

func (m *JsonHashStorageType) GetSomeEnum() JsonHashStorageType_Enum {
	if m != nil {
		return m.SomeEnum
	}
	return JsonHashStorageType_E1
}

func (m *JsonHashStorageType) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *JsonHashStorageType) GetJsonHashStorageType() *JsonHashStorageType {
	if m != nil {
		return m.JsonHashStorageType
	}
	return nil
}

func (m *JsonHashStorageType) GetSomeMessages() []*JsonHashStorageType {
	if m != nil {
		return m.SomeMessages
	}
	return nil
}

func (m *JsonHashStorageType) GetTimestamps() []*timestamp.Timestamp {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

func init() {
	proto.RegisterEnum("test.JsonStringStorageType_Enum", JsonStringStorageType_Enum_name, JsonStringStorageType_Enum_value)
	proto.RegisterEnum("test.JsonHashStorageType_Enum", JsonHashStorageType_Enum_name, JsonHashStorageType_Enum_value)
	proto.RegisterType((*JsonStringStorageType)(nil), "test.JsonStringStorageType")
	proto.RegisterType((*JsonHashStorageType)(nil), "test.JsonHashStorageType")
}

func init() { proto.RegisterFile("codec.proto", fileDescriptor_9610d574777ab505) }

var fileDescriptor_9610d574777ab505 = []byte{
	// 489 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x92, 0xcd, 0x8e, 0xd3, 0x30,
	0x14, 0x85, 0x71, 0x9b, 0x29, 0xad, 0x3b, 0x83, 0xaa, 0xf0, 0x23, 0xd3, 0x11, 0x13, 0xab, 0x2b,
	0x6f, 0x9a, 0x8a, 0xb6, 0x2a, 0x68, 0x10, 0x08, 0x21, 0x0d, 0xe2, 0x47, 0x2c, 0xc8, 0x0c, 0xeb,
	0x51, 0xd2, 0xf1, 0xb8, 0x41, 0x49, 0x6e, 0x55, 0x3b, 0x12, 0x7d, 0x3b, 0x9e, 0x81, 0x25, 0x8b,
	0xae, 0x79, 0x02, 0xd6, 0xc8, 0x76, 0x9a, 0x16, 0x48, 0xcb, 0x06, 0xb1, 0x61, 0x15, 0xe7, 0xfa,
	0x3b, 0x57, 0xd7, 0xe7, 0x1e, 0xdc, 0x9e, 0xc2, 0x15, 0x9f, 0xfa, 0xf3, 0x05, 0x28, 0x70, 0x1d,
	0xc5, 0xa5, 0xea, 0x3e, 0x12, 0xb1, 0x9a, 0xe5, 0x91, 0x3f, 0x85, 0x74, 0x20, 0xc2, 0x24, 0xfc,
	0xb4, 0x84, 0x88, 0x0f, 0x0c, 0x31, 0xed, 0x0b, 0x9e, 0xf5, 0x17, 0xfc, 0x2a, 0x96, 0xb6, 0x30,
	0x30, 0x67, 0x2b, 0xef, 0xf6, 0xb7, 0x85, 0x20, 0xc0, 0x22, 0x51, 0x7e, 0x6d, 0xfe, 0x2c, 0xaf,
	0x4f, 0x05, 0xee, 0x09, 0x00, 0x91, 0xf0, 0x0d, 0xa5, 0xe2, 0x94, 0x4b, 0x15, 0xa6, 0x73, 0x0b,
	0xf4, 0xbe, 0x3b, 0xf8, 0xee, 0x1b, 0x09, 0xd9, 0xb9, 0x5a, 0xc4, 0x99, 0x38, 0x57, 0xb0, 0x08,
	0x05, 0xbf, 0x58, 0xce, 0xb9, 0xeb, 0xe1, 0xb6, 0x84, 0x94, 0x5f, 0x4a, 0x73, 0x43, 0x10, 0x45,
	0xac, 0x15, 0x60, 0x5d, 0xb2, 0xac, 0x7b, 0x8c, 0x5b, 0x06, 0x88, 0x00, 0x12, 0x52, 0xa3, 0x88,
	0x35, 0x83, 0xa6, 0x2e, 0xbc, 0x00, 0x48, 0xdc, 0x07, 0xd8, 0xa0, 0x97, 0x71, 0xa6, 0x46, 0x43,
	0x52, 0xa7, 0x88, 0x1d, 0x04, 0x06, 0x7f, 0xad, 0x0b, 0x65, 0xf3, 0xdc, 0xde, 0x3b, 0x14, 0xb1,
	0x23, 0xdb, 0xfc, 0x83, 0xa9, 0x6c, 0xeb, 0x27, 0x63, 0x72, 0x40, 0x11, 0xab, 0x97, 0xfa, 0xc9,
	0xf8, 0x27, 0xfd, 0x64, 0x4c, 0x1a, 0x14, 0x31, 0x67, 0xa3, 0x9f, 0x8c, 0x4b, 0xfd, 0x75, 0x02,
	0xa1, 0x22, 0x37, 0x29, 0x62, 0x35, 0xab, 0x7f, 0xa9, 0x0b, 0xee, 0xd3, 0x62, 0x76, 0x9e, 0xe5,
	0x29, 0x69, 0x52, 0xc4, 0x6e, 0x0d, 0xa9, 0xaf, 0x37, 0xe3, 0x57, 0x9a, 0xe1, 0x9f, 0x65, 0x79,
	0x6a, 0x5f, 0xa7, 0x4f, 0xee, 0x63, 0xdc, 0x2a, 0x8d, 0x24, 0x2d, 0x8a, 0x58, 0x7b, 0xd8, 0xf5,
	0xad, 0xd5, 0xfe, 0xda, 0x6a, 0xff, 0x62, 0x4d, 0x04, 0x1b, 0xd8, 0x7d, 0xbf, 0xc3, 0x6e, 0x82,
	0x4d, 0x97, 0xe3, 0x3d, 0x43, 0x04, 0x3b, 0x16, 0xf5, 0x1c, 0x1f, 0x99, 0xb7, 0xa4, 0x5c, 0xca,
	0x50, 0x70, 0x49, 0xda, 0xb4, 0xfe, 0xa7, 0x56, 0x87, 0x5a, 0xf1, 0xae, 0x10, 0xb8, 0xa7, 0x18,
	0x97, 0x13, 0x4a, 0x72, 0x68, 0xe4, 0xfb, 0xde, 0xb3, 0x45, 0xf7, 0x4e, 0xb0, 0x63, 0x2c, 0x69,
	0xe0, 0xda, 0xd9, 0xc3, 0xce, 0x0d, 0xf3, 0x1d, 0x76, 0x90, 0xf9, 0x8e, 0x3a, 0xb5, 0xd3, 0x7b,
	0x9f, 0x57, 0x1e, 0xfa, 0xb2, 0xf2, 0x1a, 0x36, 0x47, 0x5f, 0x57, 0x9e, 0xf3, 0x51, 0x42, 0xd6,
	0xfb, 0xe6, 0xe0, 0xdb, 0x7a, 0xb6, 0x57, 0xa1, 0x9c, 0xfd, 0x37, 0xb1, 0x7b, 0xf2, 0x7b, 0xec,
	0x4e, 0x36, 0x6b, 0xfa, 0xc5, 0x8a, 0xbf, 0x17, 0xba, 0xb7, 0x95, 0x56, 0x17, 0x91, 0xbb, 0xbf,
	0x73, 0x80, 0xa0, 0x72, 0x41, 0xcf, 0xaa, 0xe3, 0xb6, 0xa7, 0xcd, 0xbf, 0x0b, 0xdb, 0x9d, 0x22,
	0x6c, 0xce, 0x2c, 0x94, 0xb3, 0x75, 0xd4, 0xa2, 0x86, 0xe9, 0x3a, 0xfa, 0x11, 0x00, 0x00, 0xff,
	0xff, 0x19, 0x01, 0x75, 0x09, 0x88, 0x05, 0x00, 0x00,
}
