// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: codec.proto

package test

import context "context"
import github_com_gomodule_redigo_redis "github.com/gomodule/redigo/redis"
import github_com_json_iterator_go "github.com/json-iterator/go"
import github_com_mitchellh_mapstructure "github.com/mitchellh/mapstructure"
import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/galaxyobe/protoc-gen-redis/proto"
import _ "github.com/gogo/protobuf/gogoproto"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// new JsonStringStorageType redis controller with redis pool
func (m *JsonStringStorageType) RedisController(pool *github_com_gomodule_redigo_redis.Pool) *JsonStringStorageTypeRedisController {
	return &JsonStringStorageTypeRedisController{
		pool: pool,
		m:    m,
	}
}

// JsonStringStorageType redis controller
type JsonStringStorageTypeRedisController struct {
	pool *github_com_gomodule_redigo_redis.Pool
	m    *JsonStringStorageType
}

// new JsonStringStorageType redis controller with redis pool
func NewJsonStringStorageTypeRedisController(pool *github_com_gomodule_redigo_redis.Pool) *JsonStringStorageTypeRedisController {
	return &JsonStringStorageTypeRedisController{pool: pool, m: new(JsonStringStorageType)}
}

// get JsonStringStorageType
func (r *JsonStringStorageTypeRedisController) JsonStringStorageType() *JsonStringStorageType {
	return r.m
}

// set JsonStringStorageType
func (r *JsonStringStorageTypeRedisController) SetJsonStringStorageType(m *JsonStringStorageType) {
	r.m = m
}

// store JsonStringStorageType to redis string with context and key
func (r *JsonStringStorageTypeRedisController) Store(ctx context.Context, key string) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// marshal JsonStringStorageType to []byte
	data, err := github_com_json_iterator_go.Marshal(r.m)
	if err != nil {
		return err
	}

	// use redis string store JsonStringStorageType data
	_, err = conn.Do("SET", key, data)

	return err
}

// store JsonStringStorageType to redis string with context, key and ttl expire second
func (r *JsonStringStorageTypeRedisController) StoreWithTTL(ctx context.Context, key string, ttl uint64) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// marshal JsonStringStorageType to []byte
	data, err := github_com_json_iterator_go.Marshal(r.m)
	if err != nil {
		return err
	}

	// use redis string store JsonStringStorageType data with expire second
	_, err = conn.Do("SETEX", key, ttl, data)

	return err
}

// load JsonStringStorageType from redis string with context and key
func (r *JsonStringStorageTypeRedisController) Load(ctx context.Context, key string) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// load data from redis string
	data, err := github_com_gomodule_redigo_redis.Bytes(conn.Do("GET", key))
	if err != nil {
		return err
	}

	// unmarshal data to StringStorageType
	return github_com_json_iterator_go.Unmarshal(data, r.m)
}

// new JsonHashStorageType redis controller with redis pool
func (m *JsonHashStorageType) RedisController(pool *github_com_gomodule_redigo_redis.Pool) *JsonHashStorageTypeRedisController {
	return &JsonHashStorageTypeRedisController{
		pool: pool,
		m:    m,
	}
}

// JsonHashStorageType redis controller
type JsonHashStorageTypeRedisController struct {
	pool *github_com_gomodule_redigo_redis.Pool
	m    *JsonHashStorageType
}

// new JsonHashStorageType redis controller with redis pool
func NewJsonHashStorageTypeRedisController(pool *github_com_gomodule_redigo_redis.Pool) *JsonHashStorageTypeRedisController {
	return &JsonHashStorageTypeRedisController{pool: pool, m: new(JsonHashStorageType)}
}

// get JsonHashStorageType
func (r *JsonHashStorageTypeRedisController) JsonHashStorageType() *JsonHashStorageType {
	return r.m
}

// set JsonHashStorageType
func (r *JsonHashStorageTypeRedisController) SetJsonHashStorageType(m *JsonHashStorageType) {
	r.m = m
}

// load JsonHashStorageType from redis hash with context and key
func (r *JsonHashStorageTypeRedisController) Load(ctx context.Context, key string) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// load data from redis hash
	data, err := github_com_gomodule_redigo_redis.ByteSlices(conn.Do("HGETALL", key))
	if err != nil {
		return err
	}

	// parse redis hash field name and value
	structure := make(map[string]interface{})
	for i := 0; i < len(data); i += 2 {
		switch string(data[i]) {
		case "Timestamp":
			// unmarshal Timestamp
			if r.m.Timestamp == nil {
				r.m.Timestamp = new(timestamp.Timestamp)
			}
			if err := github_com_json_iterator_go.Unmarshal(data[i+1], r.m.Timestamp); err != nil {
				return err
			}
		case "JsonHashStorageType":
			// unmarshal JsonHashStorageType
			if r.m.JsonHashStorageType == nil {
				r.m.JsonHashStorageType = new(JsonHashStorageType)
			}
			if err := github_com_json_iterator_go.Unmarshal(data[i+1], r.m.JsonHashStorageType); err != nil {
				return err
			}
		case "SomeMessages":
			// unmarshal SomeMessages
			if err := github_com_json_iterator_go.Unmarshal(data[i+1], &r.m.SomeMessages); err != nil {
				return err
			}
		case "Timestamps":
			// unmarshal Timestamps
			if err := github_com_json_iterator_go.Unmarshal(data[i+1], &r.m.Timestamps); err != nil {
				return err
			}
		default:
			structure[string(data[i])] = string(data[i+1])
		}
	}

	// use mapstructure weak decode structure to JsonHashStorageType
	return github_com_mitchellh_mapstructure.WeakDecode(structure, r.m)
}

// store JsonHashStorageType to redis hash with context and key
func (r *JsonHashStorageTypeRedisController) Store(ctx context.Context, key string) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// make args
	args := make([]interface{}, 0)

	// add redis key
	args = append(args, key)

	// add redis field and value
	args = append(args, "SomeString", r.m.SomeString)
	args = append(args, "SomeBool", r.m.SomeBool)
	args = append(args, "SomeInt32", r.m.SomeInt32)
	args = append(args, "SomeUint32", r.m.SomeUint32)
	args = append(args, "SomeInt64", r.m.SomeInt64)
	args = append(args, "SomeUint64", r.m.SomeUint64)
	args = append(args, "SomeFloat", r.m.SomeFloat)
	args = append(args, "SomeEnum", int32(r.m.SomeEnum))
	// marshal Timestamp
	if r.m.Timestamp != nil {
		Timestamp, TimestampError := github_com_json_iterator_go.Marshal(r.m.Timestamp)
		if TimestampError != nil {
			return TimestampError
		}
		args = append(args, "Timestamp", Timestamp)
	}
	// marshal JsonHashStorageType
	if r.m.JsonHashStorageType != nil {
		JsonHashStorageType, JsonHashStorageTypeError := github_com_json_iterator_go.Marshal(r.m.JsonHashStorageType)
		if JsonHashStorageTypeError != nil {
			return JsonHashStorageTypeError
		}
		args = append(args, "JsonHashStorageType", JsonHashStorageType)
	}
	// marshal SomeMessages
	if r.m.SomeMessages != nil {
		SomeMessages, SomeMessagesError := github_com_json_iterator_go.Marshal(r.m.SomeMessages)
		if SomeMessagesError != nil {
			return SomeMessagesError
		}
		args = append(args, "SomeMessages", SomeMessages)
	}
	// marshal Timestamps
	if r.m.Timestamps != nil {
		Timestamps, TimestampsError := github_com_json_iterator_go.Marshal(r.m.Timestamps)
		if TimestampsError != nil {
			return TimestampsError
		}
		args = append(args, "Timestamps", Timestamps)
	}

	// use redis hash store JsonHashStorageType data
	_, err := conn.Do("HMSET", args...)

	return err
}

// store JsonHashStorageType to redis hash with context, key and ttl expire second
func (r *JsonHashStorageTypeRedisController) StoreWithTTL(ctx context.Context, key string, ttl uint64) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// make args
	args := make([]interface{}, 0)

	// add redis key
	args = append(args, key)

	// add redis field and value
	args = append(args, "SomeString", r.m.SomeString)
	args = append(args, "SomeBool", r.m.SomeBool)
	args = append(args, "SomeInt32", r.m.SomeInt32)
	args = append(args, "SomeUint32", r.m.SomeUint32)
	args = append(args, "SomeInt64", r.m.SomeInt64)
	args = append(args, "SomeUint64", r.m.SomeUint64)
	args = append(args, "SomeFloat", r.m.SomeFloat)
	args = append(args, "SomeEnum", int32(r.m.SomeEnum))
	// marshal Timestamp
	if r.m.Timestamp != nil {
		Timestamp, TimestampError := github_com_json_iterator_go.Marshal(r.m.Timestamp)
		if TimestampError != nil {
			return TimestampError
		}
		args = append(args, "Timestamp", Timestamp)
	}
	// marshal JsonHashStorageType
	if r.m.JsonHashStorageType != nil {
		JsonHashStorageType, JsonHashStorageTypeError := github_com_json_iterator_go.Marshal(r.m.JsonHashStorageType)
		if JsonHashStorageTypeError != nil {
			return JsonHashStorageTypeError
		}
		args = append(args, "JsonHashStorageType", JsonHashStorageType)
	}
	// marshal SomeMessages
	if r.m.SomeMessages != nil {
		SomeMessages, SomeMessagesError := github_com_json_iterator_go.Marshal(r.m.SomeMessages)
		if SomeMessagesError != nil {
			return SomeMessagesError
		}
		args = append(args, "SomeMessages", SomeMessages)
	}
	// marshal Timestamps
	if r.m.Timestamps != nil {
		Timestamps, TimestampsError := github_com_json_iterator_go.Marshal(r.m.Timestamps)
		if TimestampsError != nil {
			return TimestampsError
		}
		args = append(args, "Timestamps", Timestamps)
	}

	// use redis hash store JsonHashStorageType data with expire second
	err := conn.Send("MULTI")
	if err != nil {
		return err
	}
	err = conn.Send("HMSET", args...)
	if err != nil {
		return err
	}
	err = conn.Send("EXPIRE", key, ttl)
	if err != nil {
		return err
	}
	_, err = conn.Do("EXEC")

	return err
}

// get JsonHashStorageType SomeString field value with key
func (r *JsonHashStorageTypeRedisController) GetSomeString(key string) (someString string, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeString field
	if value, err := github_com_gomodule_redigo_redis.String(conn.Do("HGET", key, "SomeString")); err != nil {
		return someString, err
	} else {
		r.m.SomeString = value
	}

	return r.m.SomeString, nil
}

// set JsonHashStorageType SomeString field with key and SomeString
func (r *JsonHashStorageTypeRedisController) SetSomeString(key string, someString string) (err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// set SomeString field
	r.m.SomeString = someString
	_, err = conn.Do("HSET", key, "SomeString", someString)

	return
}

// get JsonHashStorageType SomeBool field value with key
func (r *JsonHashStorageTypeRedisController) GetSomeBool(key string) (someBool bool, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeBool field
	if value, err := github_com_gomodule_redigo_redis.Bool(conn.Do("HGET", key, "SomeBool")); err != nil {
		return someBool, err
	} else {
		r.m.SomeBool = value
	}

	return r.m.SomeBool, nil
}

// set JsonHashStorageType SomeBool field with key and SomeBool
func (r *JsonHashStorageTypeRedisController) SetSomeBool(key string, someBool bool) (err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// set SomeBool field
	r.m.SomeBool = someBool
	_, err = conn.Do("HSET", key, "SomeBool", someBool)

	return
}

// get JsonHashStorageType SomeInt32 field value with key
func (r *JsonHashStorageTypeRedisController) GetSomeInt32(key string) (someInt32 int32, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeInt32 field
	if value, err := github_com_gomodule_redigo_redis.Int64(conn.Do("HGET", key, "SomeInt32")); err != nil {
		return someInt32, err
	} else {
		r.m.SomeInt32 = int32(value)
	}

	return r.m.SomeInt32, nil
}

// set JsonHashStorageType SomeInt32 field with key and SomeInt32
func (r *JsonHashStorageTypeRedisController) SetSomeInt32(key string, someInt32 int32) (err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// set SomeInt32 field
	r.m.SomeInt32 = someInt32
	_, err = conn.Do("HSET", key, "SomeInt32", someInt32)

	return
}

// get JsonHashStorageType SomeUint32 field value with key
func (r *JsonHashStorageTypeRedisController) GetSomeUint32(key string) (someUint32 uint32, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeUint32 field
	if value, err := github_com_gomodule_redigo_redis.Uint64(conn.Do("HGET", key, "SomeUint32")); err != nil {
		return someUint32, err
	} else {
		r.m.SomeUint32 = uint32(value)
	}

	return r.m.SomeUint32, nil
}

// set JsonHashStorageType SomeUint32 field with key and SomeUint32
func (r *JsonHashStorageTypeRedisController) SetSomeUint32(key string, someUint32 uint32) (err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// set SomeUint32 field
	r.m.SomeUint32 = someUint32
	_, err = conn.Do("HSET", key, "SomeUint32", someUint32)

	return
}

// get JsonHashStorageType SomeInt64 field value with key
func (r *JsonHashStorageTypeRedisController) GetSomeInt64(key string) (someInt64 int64, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeInt64 field
	if value, err := github_com_gomodule_redigo_redis.Int64(conn.Do("HGET", key, "SomeInt64")); err != nil {
		return someInt64, err
	} else {
		r.m.SomeInt64 = value
	}

	return r.m.SomeInt64, nil
}

// set JsonHashStorageType SomeInt64 field with key and SomeInt64
func (r *JsonHashStorageTypeRedisController) SetSomeInt64(key string, someInt64 int64) (err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// set SomeInt64 field
	r.m.SomeInt64 = someInt64
	_, err = conn.Do("HSET", key, "SomeInt64", someInt64)

	return
}

// get JsonHashStorageType SomeUint64 field value with key
func (r *JsonHashStorageTypeRedisController) GetSomeUint64(key string) (someUint64 uint64, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeUint64 field
	if value, err := github_com_gomodule_redigo_redis.Uint64(conn.Do("HGET", key, "SomeUint64")); err != nil {
		return someUint64, err
	} else {
		r.m.SomeUint64 = value
	}

	return r.m.SomeUint64, nil
}

// set JsonHashStorageType SomeUint64 field with key and SomeUint64
func (r *JsonHashStorageTypeRedisController) SetSomeUint64(key string, someUint64 uint64) (err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// set SomeUint64 field
	r.m.SomeUint64 = someUint64
	_, err = conn.Do("HSET", key, "SomeUint64", someUint64)

	return
}

// get JsonHashStorageType SomeFloat field value with key
func (r *JsonHashStorageTypeRedisController) GetSomeFloat(key string) (someFloat float32, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeFloat field
	if value, err := github_com_gomodule_redigo_redis.Float64(conn.Do("HGET", key, "SomeFloat")); err != nil {
		return someFloat, err
	} else {
		r.m.SomeFloat = float32(value)
	}

	return r.m.SomeFloat, nil
}

// set JsonHashStorageType SomeFloat field with key and SomeFloat
func (r *JsonHashStorageTypeRedisController) SetSomeFloat(key string, someFloat float32) (err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// set SomeFloat field
	r.m.SomeFloat = someFloat
	_, err = conn.Do("HSET", key, "SomeFloat", someFloat)

	return
}

// get JsonHashStorageType SomeEnum field value with key
func (r *JsonHashStorageTypeRedisController) GetSomeEnum(key string) (someEnum JsonHashStorageType_Enum, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeEnum field
	if value, err := github_com_gomodule_redigo_redis.Int64(conn.Do("HGET", key, "SomeEnum")); err != nil {
		return someEnum, err
	} else {
		r.m.SomeEnum = JsonHashStorageType_Enum(value)
	}

	return r.m.SomeEnum, nil
}

// set JsonHashStorageType SomeEnum field with key and SomeEnum
func (r *JsonHashStorageTypeRedisController) SetSomeEnum(key string, someEnum JsonHashStorageType_Enum) (err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// set SomeEnum field
	r.m.SomeEnum = someEnum
	_, err = conn.Do("HSET", key, "SomeEnum", int32(someEnum))

	return
}

// get JsonHashStorageType Timestamp field value with key
func (r *JsonHashStorageTypeRedisController) GetTimestamp(key string) (ret *timestamp.Timestamp, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get Timestamp field
	if value, err := github_com_gomodule_redigo_redis.Bytes(conn.Do("HGET", key, "Timestamp")); err != nil {
		return ret, err
	} else {
		// unmarshal Timestamp
		if r.m.Timestamp == nil {
			r.m.Timestamp = new(timestamp.Timestamp)
		}
		if err = github_com_json_iterator_go.Unmarshal(value, r.m.Timestamp); err != nil {
			return ret, err
		}
	}

	return r.m.Timestamp, nil
}

// set JsonHashStorageType Timestamp field with key and Timestamp
func (r *JsonHashStorageTypeRedisController) SetTimestamp(key string, timestamp *timestamp.Timestamp) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// marshal Timestamp
	r.m.Timestamp = timestamp
	if data, err := github_com_json_iterator_go.Marshal(r.m.Timestamp); err != nil {
		return err
	} else {
		// set Timestamp field
		_, err = conn.Do("HSET", key, "Timestamp", data)
		return err
	}

	return nil
}

// get JsonHashStorageType JsonHashStorageType field value with key
func (r *JsonHashStorageTypeRedisController) GetJsonHashStorageType(key string) (ret *JsonHashStorageType, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get JsonHashStorageType field
	if value, err := github_com_gomodule_redigo_redis.Bytes(conn.Do("HGET", key, "JsonHashStorageType")); err != nil {
		return ret, err
	} else {
		// unmarshal JsonHashStorageType
		if r.m.JsonHashStorageType == nil {
			r.m.JsonHashStorageType = new(JsonHashStorageType)
		}
		if err = github_com_json_iterator_go.Unmarshal(value, r.m.JsonHashStorageType); err != nil {
			return ret, err
		}
	}

	return r.m.JsonHashStorageType, nil
}

// set JsonHashStorageType JsonHashStorageType field with key and JsonHashStorageType
func (r *JsonHashStorageTypeRedisController) SetJsonHashStorageTypeField(key string, JsonHashStorageType *JsonHashStorageType) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// marshal JsonHashStorageType
	r.m.JsonHashStorageType = JsonHashStorageType
	if data, err := github_com_json_iterator_go.Marshal(r.m.JsonHashStorageType); err != nil {
		return err
	} else {
		// set JsonHashStorageType field
		_, err = conn.Do("HSET", key, "JsonHashStorageType", data)
		return err
	}

	return nil
}

// get JsonHashStorageType SomeMessages field value with key
func (r *JsonHashStorageTypeRedisController) GetSomeMessages(key string) (ret []*JsonHashStorageType, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeMessages field
	if value, err := github_com_gomodule_redigo_redis.Bytes(conn.Do("HGET", key, "SomeMessages")); err != nil {
		return ret, err
	} else {
		// unmarshal SomeMessages
		if err = github_com_json_iterator_go.Unmarshal(value, &r.m.SomeMessages); err != nil {
			return ret, err
		}
	}

	return r.m.SomeMessages, nil
}

// set JsonHashStorageType SomeMessages field with key and SomeMessages
func (r *JsonHashStorageTypeRedisController) SetSomeMessages(key string, someMessages []*JsonHashStorageType) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// marshal SomeMessages
	r.m.SomeMessages = someMessages
	if data, err := github_com_json_iterator_go.Marshal(r.m.SomeMessages); err != nil {
		return err
	} else {
		// set SomeMessages field
		_, err = conn.Do("HSET", key, "SomeMessages", data)
		return err
	}

	return nil
}

// get JsonHashStorageType Timestamps field value with key
func (r *JsonHashStorageTypeRedisController) GetTimestamps(key string) (ret []*timestamp.Timestamp, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get Timestamps field
	if value, err := github_com_gomodule_redigo_redis.Bytes(conn.Do("HGET", key, "Timestamps")); err != nil {
		return ret, err
	} else {
		// unmarshal Timestamps
		if err = github_com_json_iterator_go.Unmarshal(value, &r.m.Timestamps); err != nil {
			return ret, err
		}
	}

	return r.m.Timestamps, nil
}

// set JsonHashStorageType Timestamps field with key and Timestamps
func (r *JsonHashStorageTypeRedisController) SetTimestamps(key string, timestamps []*timestamp.Timestamp) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// marshal Timestamps
	r.m.Timestamps = timestamps
	if data, err := github_com_json_iterator_go.Marshal(r.m.Timestamps); err != nil {
		return err
	} else {
		// set Timestamps field
		_, err = conn.Do("HSET", key, "Timestamps", data)
		return err
	}

	return nil
}
