// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test.proto

package test

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
	_ "protoc-gen-redis/proto"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type EnabledWithTTL struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnabledWithTTL) Reset()         { *m = EnabledWithTTL{} }
func (m *EnabledWithTTL) String() string { return proto.CompactTextString(m) }
func (*EnabledWithTTL) ProtoMessage()    {}
func (*EnabledWithTTL) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{0}
}

func (m *EnabledWithTTL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnabledWithTTL.Unmarshal(m, b)
}
func (m *EnabledWithTTL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnabledWithTTL.Marshal(b, m, deterministic)
}
func (m *EnabledWithTTL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnabledWithTTL.Merge(m, src)
}
func (m *EnabledWithTTL) XXX_Size() int {
	return xxx_messageInfo_EnabledWithTTL.Size(m)
}
func (m *EnabledWithTTL) XXX_DiscardUnknown() {
	xxx_messageInfo_EnabledWithTTL.DiscardUnknown(m)
}

var xxx_messageInfo_EnabledWithTTL proto.InternalMessageInfo

func (m *EnabledWithTTL) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

type EnabledWithTTL2 struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnabledWithTTL2) Reset()         { *m = EnabledWithTTL2{} }
func (m *EnabledWithTTL2) String() string { return proto.CompactTextString(m) }
func (*EnabledWithTTL2) ProtoMessage()    {}
func (*EnabledWithTTL2) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{1}
}

func (m *EnabledWithTTL2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnabledWithTTL2.Unmarshal(m, b)
}
func (m *EnabledWithTTL2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnabledWithTTL2.Marshal(b, m, deterministic)
}
func (m *EnabledWithTTL2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnabledWithTTL2.Merge(m, src)
}
func (m *EnabledWithTTL2) XXX_Size() int {
	return xxx_messageInfo_EnabledWithTTL2.Size(m)
}
func (m *EnabledWithTTL2) XXX_DiscardUnknown() {
	xxx_messageInfo_EnabledWithTTL2.DiscardUnknown(m)
}

var xxx_messageInfo_EnabledWithTTL2 proto.InternalMessageInfo

func (m *EnabledWithTTL2) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

type EnabledWithoutTTL struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnabledWithoutTTL) Reset()         { *m = EnabledWithoutTTL{} }
func (m *EnabledWithoutTTL) String() string { return proto.CompactTextString(m) }
func (*EnabledWithoutTTL) ProtoMessage()    {}
func (*EnabledWithoutTTL) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{2}
}

func (m *EnabledWithoutTTL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnabledWithoutTTL.Unmarshal(m, b)
}
func (m *EnabledWithoutTTL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnabledWithoutTTL.Marshal(b, m, deterministic)
}
func (m *EnabledWithoutTTL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnabledWithoutTTL.Merge(m, src)
}
func (m *EnabledWithoutTTL) XXX_Size() int {
	return xxx_messageInfo_EnabledWithoutTTL.Size(m)
}
func (m *EnabledWithoutTTL) XXX_DiscardUnknown() {
	xxx_messageInfo_EnabledWithoutTTL.DiscardUnknown(m)
}

var xxx_messageInfo_EnabledWithoutTTL proto.InternalMessageInfo

func (m *EnabledWithoutTTL) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

type Disabled struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disabled) Reset()         { *m = Disabled{} }
func (m *Disabled) String() string { return proto.CompactTextString(m) }
func (*Disabled) ProtoMessage()    {}
func (*Disabled) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{3}
}

func (m *Disabled) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disabled.Unmarshal(m, b)
}
func (m *Disabled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disabled.Marshal(b, m, deterministic)
}
func (m *Disabled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disabled.Merge(m, src)
}
func (m *Disabled) XXX_Size() int {
	return xxx_messageInfo_Disabled.Size(m)
}
func (m *Disabled) XXX_DiscardUnknown() {
	xxx_messageInfo_Disabled.DiscardUnknown(m)
}

var xxx_messageInfo_Disabled proto.InternalMessageInfo

func (m *Disabled) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

type Disabled2 struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disabled2) Reset()         { *m = Disabled2{} }
func (m *Disabled2) String() string { return proto.CompactTextString(m) }
func (*Disabled2) ProtoMessage()    {}
func (*Disabled2) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{4}
}

func (m *Disabled2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disabled2.Unmarshal(m, b)
}
func (m *Disabled2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disabled2.Marshal(b, m, deterministic)
}
func (m *Disabled2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disabled2.Merge(m, src)
}
func (m *Disabled2) XXX_Size() int {
	return xxx_messageInfo_Disabled2.Size(m)
}
func (m *Disabled2) XXX_DiscardUnknown() {
	xxx_messageInfo_Disabled2.DiscardUnknown(m)
}

var xxx_messageInfo_Disabled2 proto.InternalMessageInfo

func (m *Disabled2) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

type Disabled3 struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disabled3) Reset()         { *m = Disabled3{} }
func (m *Disabled3) String() string { return proto.CompactTextString(m) }
func (*Disabled3) ProtoMessage()    {}
func (*Disabled3) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{5}
}

func (m *Disabled3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disabled3.Unmarshal(m, b)
}
func (m *Disabled3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disabled3.Marshal(b, m, deterministic)
}
func (m *Disabled3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disabled3.Merge(m, src)
}
func (m *Disabled3) XXX_Size() int {
	return xxx_messageInfo_Disabled3.Size(m)
}
func (m *Disabled3) XXX_DiscardUnknown() {
	xxx_messageInfo_Disabled3.DiscardUnknown(m)
}

var xxx_messageInfo_Disabled3 proto.InternalMessageInfo

func (m *Disabled3) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

type Disabled4 struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disabled4) Reset()         { *m = Disabled4{} }
func (m *Disabled4) String() string { return proto.CompactTextString(m) }
func (*Disabled4) ProtoMessage()    {}
func (*Disabled4) Descriptor() ([]byte, []int) {
	return fileDescriptor_c161fcfdc0c3ff1e, []int{6}
}

func (m *Disabled4) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disabled4.Unmarshal(m, b)
}
func (m *Disabled4) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disabled4.Marshal(b, m, deterministic)
}
func (m *Disabled4) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disabled4.Merge(m, src)
}
func (m *Disabled4) XXX_Size() int {
	return xxx_messageInfo_Disabled4.Size(m)
}
func (m *Disabled4) XXX_DiscardUnknown() {
	xxx_messageInfo_Disabled4.DiscardUnknown(m)
}

var xxx_messageInfo_Disabled4 proto.InternalMessageInfo

func (m *Disabled4) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

func init() {
	proto.RegisterType((*EnabledWithTTL)(nil), "test.EnabledWithTTL")
	proto.RegisterType((*EnabledWithTTL2)(nil), "test.EnabledWithTTL2")
	proto.RegisterType((*EnabledWithoutTTL)(nil), "test.EnabledWithoutTTL")
	proto.RegisterType((*Disabled)(nil), "test.Disabled")
	proto.RegisterType((*Disabled2)(nil), "test.Disabled2")
	proto.RegisterType((*Disabled3)(nil), "test.Disabled3")
	proto.RegisterType((*Disabled4)(nil), "test.Disabled4")
}

func init() { proto.RegisterFile("test.proto", fileDescriptor_c161fcfdc0c3ff1e) }

var fileDescriptor_c161fcfdc0c3ff1e = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2a, 0x49, 0x2d, 0x2e,
	0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x01, 0xb1, 0xa5, 0x94, 0xc0, 0x9c, 0x64, 0xdd,
	0xf4, 0xd4, 0x3c, 0xdd, 0xa2, 0xd4, 0x94, 0xcc, 0x62, 0x7d, 0xb0, 0x80, 0x3e, 0x98, 0x0d, 0x51,
	0xa9, 0x64, 0xcb, 0xc5, 0xe7, 0x9a, 0x97, 0x98, 0x94, 0x93, 0x9a, 0x12, 0x9e, 0x59, 0x92, 0x11,
	0x12, 0xe2, 0x23, 0xa4, 0xc8, 0xc5, 0x53, 0x9c, 0x9f, 0x9b, 0x1a, 0x9f, 0x99, 0x57, 0x92, 0x9a,
	0x9e, 0x5a, 0x24, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1a, 0xc4, 0x0d, 0x12, 0xf3, 0x84, 0x08, 0x59,
	0x71, 0x1c, 0xb8, 0x27, 0xcf, 0x78, 0xe2, 0x9e, 0x3c, 0xa3, 0x92, 0x15, 0x17, 0x3f, 0xaa, 0x76,
	0x23, 0x62, 0xf4, 0xb3, 0x80, 0xf4, 0x2b, 0x39, 0x70, 0x09, 0x22, 0xe9, 0xcd, 0x2f, 0x2d, 0x21,
	0xd1, 0x76, 0x06, 0x25, 0x73, 0x2e, 0x0e, 0x97, 0xcc, 0x62, 0xb0, 0x11, 0xc4, 0x6a, 0x64, 0x00,
	0x6b, 0xb4, 0xe0, 0xe2, 0x84, 0x69, 0x34, 0x22, 0x45, 0x27, 0xa3, 0x92, 0x09, 0x42, 0xa7, 0x31,
	0x51, 0x5e, 0x05, 0xeb, 0xd2, 0x43, 0xe8, 0x32, 0x21, 0x42, 0x57, 0x12, 0x1b, 0x38, 0x72, 0x8c,
	0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0x91, 0xb9, 0xd0, 0x4b, 0xd4, 0x01, 0x00, 0x00,
}
