// Code generated by protoc-gen-go. DO NOT EDIT.
// source: test/test.proto

package test

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "protoc-gen-redis/proto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Demo struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Demo) Reset()         { *m = Demo{} }
func (m *Demo) String() string { return proto.CompactTextString(m) }
func (*Demo) ProtoMessage()    {}
func (*Demo) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_e53c0ec0feb6ac13, []int{0}
}
func (m *Demo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Demo.Unmarshal(m, b)
}
func (m *Demo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Demo.Marshal(b, m, deterministic)
}
func (dst *Demo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Demo.Merge(dst, src)
}
func (m *Demo) XXX_Size() int {
	return xxx_messageInfo_Demo.Size(m)
}
func (m *Demo) XXX_DiscardUnknown() {
	xxx_messageInfo_Demo.DiscardUnknown(m)
}

var xxx_messageInfo_Demo proto.InternalMessageInfo

func (m *Demo) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

type EnabledWithTTL2 struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnabledWithTTL2) Reset()         { *m = EnabledWithTTL2{} }
func (m *EnabledWithTTL2) String() string { return proto.CompactTextString(m) }
func (*EnabledWithTTL2) ProtoMessage()    {}
func (*EnabledWithTTL2) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_e53c0ec0feb6ac13, []int{1}
}
func (m *EnabledWithTTL2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnabledWithTTL2.Unmarshal(m, b)
}
func (m *EnabledWithTTL2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnabledWithTTL2.Marshal(b, m, deterministic)
}
func (dst *EnabledWithTTL2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnabledWithTTL2.Merge(dst, src)
}
func (m *EnabledWithTTL2) XXX_Size() int {
	return xxx_messageInfo_EnabledWithTTL2.Size(m)
}
func (m *EnabledWithTTL2) XXX_DiscardUnknown() {
	xxx_messageInfo_EnabledWithTTL2.DiscardUnknown(m)
}

var xxx_messageInfo_EnabledWithTTL2 proto.InternalMessageInfo

func (m *EnabledWithTTL2) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

type EnabledWithoutTTL struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnabledWithoutTTL) Reset()         { *m = EnabledWithoutTTL{} }
func (m *EnabledWithoutTTL) String() string { return proto.CompactTextString(m) }
func (*EnabledWithoutTTL) ProtoMessage()    {}
func (*EnabledWithoutTTL) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_e53c0ec0feb6ac13, []int{2}
}
func (m *EnabledWithoutTTL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnabledWithoutTTL.Unmarshal(m, b)
}
func (m *EnabledWithoutTTL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnabledWithoutTTL.Marshal(b, m, deterministic)
}
func (dst *EnabledWithoutTTL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnabledWithoutTTL.Merge(dst, src)
}
func (m *EnabledWithoutTTL) XXX_Size() int {
	return xxx_messageInfo_EnabledWithoutTTL.Size(m)
}
func (m *EnabledWithoutTTL) XXX_DiscardUnknown() {
	xxx_messageInfo_EnabledWithoutTTL.DiscardUnknown(m)
}

var xxx_messageInfo_EnabledWithoutTTL proto.InternalMessageInfo

func (m *EnabledWithoutTTL) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

type Disabled struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disabled) Reset()         { *m = Disabled{} }
func (m *Disabled) String() string { return proto.CompactTextString(m) }
func (*Disabled) ProtoMessage()    {}
func (*Disabled) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_e53c0ec0feb6ac13, []int{3}
}
func (m *Disabled) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disabled.Unmarshal(m, b)
}
func (m *Disabled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disabled.Marshal(b, m, deterministic)
}
func (dst *Disabled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disabled.Merge(dst, src)
}
func (m *Disabled) XXX_Size() int {
	return xxx_messageInfo_Disabled.Size(m)
}
func (m *Disabled) XXX_DiscardUnknown() {
	xxx_messageInfo_Disabled.DiscardUnknown(m)
}

var xxx_messageInfo_Disabled proto.InternalMessageInfo

func (m *Disabled) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

type Disabled2 struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disabled2) Reset()         { *m = Disabled2{} }
func (m *Disabled2) String() string { return proto.CompactTextString(m) }
func (*Disabled2) ProtoMessage()    {}
func (*Disabled2) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_e53c0ec0feb6ac13, []int{4}
}
func (m *Disabled2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disabled2.Unmarshal(m, b)
}
func (m *Disabled2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disabled2.Marshal(b, m, deterministic)
}
func (dst *Disabled2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disabled2.Merge(dst, src)
}
func (m *Disabled2) XXX_Size() int {
	return xxx_messageInfo_Disabled2.Size(m)
}
func (m *Disabled2) XXX_DiscardUnknown() {
	xxx_messageInfo_Disabled2.DiscardUnknown(m)
}

var xxx_messageInfo_Disabled2 proto.InternalMessageInfo

func (m *Disabled2) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

type Disabled3 struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disabled3) Reset()         { *m = Disabled3{} }
func (m *Disabled3) String() string { return proto.CompactTextString(m) }
func (*Disabled3) ProtoMessage()    {}
func (*Disabled3) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_e53c0ec0feb6ac13, []int{5}
}
func (m *Disabled3) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disabled3.Unmarshal(m, b)
}
func (m *Disabled3) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disabled3.Marshal(b, m, deterministic)
}
func (dst *Disabled3) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disabled3.Merge(dst, src)
}
func (m *Disabled3) XXX_Size() int {
	return xxx_messageInfo_Disabled3.Size(m)
}
func (m *Disabled3) XXX_DiscardUnknown() {
	xxx_messageInfo_Disabled3.DiscardUnknown(m)
}

var xxx_messageInfo_Disabled3 proto.InternalMessageInfo

func (m *Disabled3) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

type Disabled4 struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Disabled4) Reset()         { *m = Disabled4{} }
func (m *Disabled4) String() string { return proto.CompactTextString(m) }
func (*Disabled4) ProtoMessage()    {}
func (*Disabled4) Descriptor() ([]byte, []int) {
	return fileDescriptor_test_e53c0ec0feb6ac13, []int{6}
}
func (m *Disabled4) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Disabled4.Unmarshal(m, b)
}
func (m *Disabled4) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Disabled4.Marshal(b, m, deterministic)
}
func (dst *Disabled4) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Disabled4.Merge(dst, src)
}
func (m *Disabled4) XXX_Size() int {
	return xxx_messageInfo_Disabled4.Size(m)
}
func (m *Disabled4) XXX_DiscardUnknown() {
	xxx_messageInfo_Disabled4.DiscardUnknown(m)
}

var xxx_messageInfo_Disabled4 proto.InternalMessageInfo

func (m *Disabled4) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

func init() {
	proto.RegisterType((*Demo)(nil), "test.Demo")
	proto.RegisterType((*EnabledWithTTL2)(nil), "test.EnabledWithTTL2")
	proto.RegisterType((*EnabledWithoutTTL)(nil), "test.EnabledWithoutTTL")
	proto.RegisterType((*Disabled)(nil), "test.Disabled")
	proto.RegisterType((*Disabled2)(nil), "test.Disabled2")
	proto.RegisterType((*Disabled3)(nil), "test.Disabled3")
	proto.RegisterType((*Disabled4)(nil), "test.Disabled4")
}

func init() { proto.RegisterFile("test/test.proto", fileDescriptor_test_e53c0ec0feb6ac13) }

var fileDescriptor_test_e53c0ec0feb6ac13 = []byte{
	// 238 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x49, 0x2d, 0x2e,
	0xd1, 0x07, 0x11, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6, 0x94, 0x12, 0x98,
	0x93, 0xac, 0x9b, 0x9e, 0x9a, 0xa7, 0x5b, 0x94, 0x9a, 0x92, 0x59, 0xac, 0x0f, 0x16, 0xd0, 0x07,
	0xb3, 0x21, 0x2a, 0xa5, 0x74, 0xd3, 0x33, 0x4b, 0x32, 0x4a, 0x93, 0xf4, 0x92, 0xf3, 0x73, 0xf5,
	0xd3, 0xf3, 0xd3, 0xf3, 0x21, 0x4a, 0x92, 0x4a, 0xd3, 0xc0, 0x3c, 0x88, 0x7a, 0x10, 0x0b, 0xa2,
	0x5c, 0xc9, 0x9a, 0x8b, 0xc5, 0x25, 0x35, 0x37, 0x5f, 0x48, 0x91, 0x8b, 0xa7, 0x38, 0x3f, 0x37,
	0x35, 0x3e, 0x33, 0xaf, 0x24, 0x35, 0x3d, 0xb5, 0x48, 0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x88,
	0x1b, 0x24, 0xe6, 0x09, 0x11, 0xb2, 0x12, 0x38, 0x70, 0x4f, 0x9e, 0xf1, 0xc4, 0x3d, 0x79, 0xc6,
	0x4b, 0xf7, 0xe4, 0x59, 0x32, 0x12, 0x8b, 0x33, 0x94, 0xac, 0xb8, 0xf8, 0x5d, 0xf3, 0x12, 0x93,
	0x72, 0x52, 0x53, 0xc2, 0x33, 0x4b, 0x32, 0x42, 0x42, 0x7c, 0x8c, 0x88, 0x31, 0x87, 0x05, 0x64,
	0x8e, 0x92, 0x03, 0x97, 0x20, 0x92, 0xde, 0xfc, 0xd2, 0x92, 0x90, 0x10, 0x1f, 0x62, 0x74, 0x73,
	0x40, 0x5d, 0xc1, 0xa0, 0x64, 0xce, 0xc5, 0xe1, 0x92, 0x59, 0x0c, 0x36, 0x82, 0x58, 0x8d, 0x0c,
	0x60, 0x8d, 0x16, 0x5c, 0x9c, 0x30, 0x8d, 0x46, 0xa4, 0xe8, 0x64, 0x54, 0x32, 0x41, 0xe8, 0x34,
	0x26, 0xca, 0xab, 0x60, 0x5d, 0x7a, 0x08, 0x5d, 0x26, 0x44, 0xe8, 0x4a, 0x62, 0x03, 0x47, 0x8d,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x0e, 0xd3, 0xc8, 0xae, 0x06, 0x02, 0x00, 0x00,
}
