// Code generated by protoc-gen-go. DO NOT EDIT.
// source: type.proto

package test

import (
	fmt "fmt"
	_ "github.com/galaxyobe/protoc-gen-redis/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StringStorageType_Enum int32

const (
	StringStorageType_E1 StringStorageType_Enum = 0
	StringStorageType_E2 StringStorageType_Enum = 1
	StringStorageType_E3 StringStorageType_Enum = 2
)

var StringStorageType_Enum_name = map[int32]string{
	0: "E1",
	1: "E2",
	2: "E3",
}

var StringStorageType_Enum_value = map[string]int32{
	"E1": 0,
	"E2": 1,
	"E3": 2,
}

func (x StringStorageType_Enum) String() string {
	return proto.EnumName(StringStorageType_Enum_name, int32(x))
}

func (StringStorageType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{0, 0}
}

type HashStorageType_Enum int32

const (
	HashStorageType_E1 HashStorageType_Enum = 0
	HashStorageType_E2 HashStorageType_Enum = 1
	HashStorageType_E3 HashStorageType_Enum = 2
)

var HashStorageType_Enum_name = map[int32]string{
	0: "E1",
	1: "E2",
	2: "E3",
}

var HashStorageType_Enum_value = map[string]int32{
	"E1": 0,
	"E2": 1,
	"E3": 2,
}

func (x HashStorageType_Enum) String() string {
	return proto.EnumName(HashStorageType_Enum_name, int32(x))
}

func (HashStorageType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{1, 0}
}

type StringStorageType struct {
	SomeString           string                 `protobuf:"bytes,1,opt,name=some_string,json=someString,proto3" json:"some_string,omitempty"`
	SomeBool             bool                   `protobuf:"varint,2,opt,name=some_bool,json=someBool,proto3" json:"some_bool,omitempty"`
	SomeInt32            int32                  `protobuf:"varint,3,opt,name=some_int32,json=someInt32,proto3" json:"some_int32,omitempty"`
	SomeUint32           uint32                 `protobuf:"varint,4,opt,name=some_uint32,json=someUint32,proto3" json:"some_uint32,omitempty"`
	SomeInt64            int64                  `protobuf:"varint,5,opt,name=some_int64,json=someInt64,proto3" json:"some_int64,omitempty"`
	SomeUint64           uint64                 `protobuf:"varint,6,opt,name=some_uint64,json=someUint64,proto3" json:"some_uint64,omitempty"`
	SomeFloat            float32                `protobuf:"fixed32,7,opt,name=some_float,json=someFloat,proto3" json:"some_float,omitempty"`
	SomeEnum             StringStorageType_Enum `protobuf:"varint,8,opt,name=some_enum,json=someEnum,proto3,enum=test.StringStorageType_Enum" json:"some_enum,omitempty"`
	Timestamp            *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	StringStorageType    *StringStorageType     `protobuf:"bytes,10,opt,name=StringStorageType,proto3" json:"StringStorageType,omitempty"`
	SomeMessages         []*StringStorageType   `protobuf:"bytes,11,rep,name=some_messages,json=someMessages,proto3" json:"some_messages,omitempty"`
	Timestamps           []*timestamp.Timestamp `protobuf:"bytes,12,rep,name=timestamps,proto3" json:"timestamps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StringStorageType) Reset()         { *m = StringStorageType{} }
func (m *StringStorageType) String() string { return proto.CompactTextString(m) }
func (*StringStorageType) ProtoMessage()    {}
func (*StringStorageType) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{0}
}

func (m *StringStorageType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringStorageType.Unmarshal(m, b)
}
func (m *StringStorageType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringStorageType.Marshal(b, m, deterministic)
}
func (m *StringStorageType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringStorageType.Merge(m, src)
}
func (m *StringStorageType) XXX_Size() int {
	return xxx_messageInfo_StringStorageType.Size(m)
}
func (m *StringStorageType) XXX_DiscardUnknown() {
	xxx_messageInfo_StringStorageType.DiscardUnknown(m)
}

var xxx_messageInfo_StringStorageType proto.InternalMessageInfo

func (m *StringStorageType) GetSomeString() string {
	if m != nil {
		return m.SomeString
	}
	return ""
}

func (m *StringStorageType) GetSomeBool() bool {
	if m != nil {
		return m.SomeBool
	}
	return false
}

func (m *StringStorageType) GetSomeInt32() int32 {
	if m != nil {
		return m.SomeInt32
	}
	return 0
}

func (m *StringStorageType) GetSomeUint32() uint32 {
	if m != nil {
		return m.SomeUint32
	}
	return 0
}

func (m *StringStorageType) GetSomeInt64() int64 {
	if m != nil {
		return m.SomeInt64
	}
	return 0
}

func (m *StringStorageType) GetSomeUint64() uint64 {
	if m != nil {
		return m.SomeUint64
	}
	return 0
}

func (m *StringStorageType) GetSomeFloat() float32 {
	if m != nil {
		return m.SomeFloat
	}
	return 0
}

func (m *StringStorageType) GetSomeEnum() StringStorageType_Enum {
	if m != nil {
		return m.SomeEnum
	}
	return StringStorageType_E1
}

func (m *StringStorageType) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *StringStorageType) GetStringStorageType() *StringStorageType {
	if m != nil {
		return m.StringStorageType
	}
	return nil
}

func (m *StringStorageType) GetSomeMessages() []*StringStorageType {
	if m != nil {
		return m.SomeMessages
	}
	return nil
}

func (m *StringStorageType) GetTimestamps() []*timestamp.Timestamp {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

type HashStorageType struct {
	SomeString           string                 `protobuf:"bytes,1,opt,name=some_string,json=someString,proto3" json:"some_string,omitempty"`
	SomeBool             bool                   `protobuf:"varint,2,opt,name=some_bool,json=someBool,proto3" json:"some_bool,omitempty"`
	SomeInt32            int32                  `protobuf:"varint,3,opt,name=some_int32,json=someInt32,proto3" json:"some_int32,omitempty"`
	SomeUint32           uint32                 `protobuf:"varint,4,opt,name=some_uint32,json=someUint32,proto3" json:"some_uint32,omitempty"`
	SomeInt64            int64                  `protobuf:"varint,5,opt,name=some_int64,json=someInt64,proto3" json:"some_int64,omitempty"`
	SomeUint64           uint64                 `protobuf:"varint,6,opt,name=some_uint64,json=someUint64,proto3" json:"some_uint64,omitempty"`
	SomeFloat            float32                `protobuf:"fixed32,7,opt,name=some_float,json=someFloat,proto3" json:"some_float,omitempty"`
	SomeEnum             HashStorageType_Enum   `protobuf:"varint,8,opt,name=some_enum,json=someEnum,proto3,enum=test.HashStorageType_Enum" json:"some_enum,omitempty"`
	Timestamp            *timestamp.Timestamp   `protobuf:"bytes,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	HashStorageType      *HashStorageType       `protobuf:"bytes,10,opt,name=HashStorageType,proto3" json:"HashStorageType,omitempty"`
	SomeMessages         []*HashStorageType     `protobuf:"bytes,11,rep,name=some_messages,json=someMessages,proto3" json:"some_messages,omitempty"`
	Timestamps           []*timestamp.Timestamp `protobuf:"bytes,12,rep,name=timestamps,proto3" json:"timestamps,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *HashStorageType) Reset()         { *m = HashStorageType{} }
func (m *HashStorageType) String() string { return proto.CompactTextString(m) }
func (*HashStorageType) ProtoMessage()    {}
func (*HashStorageType) Descriptor() ([]byte, []int) {
	return fileDescriptor_8eaed4801c3a9059, []int{1}
}

func (m *HashStorageType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashStorageType.Unmarshal(m, b)
}
func (m *HashStorageType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashStorageType.Marshal(b, m, deterministic)
}
func (m *HashStorageType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashStorageType.Merge(m, src)
}
func (m *HashStorageType) XXX_Size() int {
	return xxx_messageInfo_HashStorageType.Size(m)
}
func (m *HashStorageType) XXX_DiscardUnknown() {
	xxx_messageInfo_HashStorageType.DiscardUnknown(m)
}

var xxx_messageInfo_HashStorageType proto.InternalMessageInfo

func (m *HashStorageType) GetSomeString() string {
	if m != nil {
		return m.SomeString
	}
	return ""
}

func (m *HashStorageType) GetSomeBool() bool {
	if m != nil {
		return m.SomeBool
	}
	return false
}

func (m *HashStorageType) GetSomeInt32() int32 {
	if m != nil {
		return m.SomeInt32
	}
	return 0
}

func (m *HashStorageType) GetSomeUint32() uint32 {
	if m != nil {
		return m.SomeUint32
	}
	return 0
}

func (m *HashStorageType) GetSomeInt64() int64 {
	if m != nil {
		return m.SomeInt64
	}
	return 0
}

func (m *HashStorageType) GetSomeUint64() uint64 {
	if m != nil {
		return m.SomeUint64
	}
	return 0
}

func (m *HashStorageType) GetSomeFloat() float32 {
	if m != nil {
		return m.SomeFloat
	}
	return 0
}

func (m *HashStorageType) GetSomeEnum() HashStorageType_Enum {
	if m != nil {
		return m.SomeEnum
	}
	return HashStorageType_E1
}

func (m *HashStorageType) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *HashStorageType) GetHashStorageType() *HashStorageType {
	if m != nil {
		return m.HashStorageType
	}
	return nil
}

func (m *HashStorageType) GetSomeMessages() []*HashStorageType {
	if m != nil {
		return m.SomeMessages
	}
	return nil
}

func (m *HashStorageType) GetTimestamps() []*timestamp.Timestamp {
	if m != nil {
		return m.Timestamps
	}
	return nil
}

func init() {
	proto.RegisterEnum("test.StringStorageType_Enum", StringStorageType_Enum_name, StringStorageType_Enum_value)
	proto.RegisterEnum("test.HashStorageType_Enum", HashStorageType_Enum_name, HashStorageType_Enum_value)
	proto.RegisterType((*StringStorageType)(nil), "test.StringStorageType")
	proto.RegisterType((*HashStorageType)(nil), "test.HashStorageType")
}

func init() { proto.RegisterFile("type.proto", fileDescriptor_8eaed4801c3a9059) }

var fileDescriptor_8eaed4801c3a9059 = []byte{
	// 469 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x92, 0x4f, 0x8f, 0x12, 0x31,
	0x18, 0xc6, 0x2d, 0xcc, 0x22, 0x14, 0x76, 0xc5, 0x26, 0xc6, 0x06, 0xff, 0xd0, 0x70, 0xea, 0x85,
	0x12, 0x81, 0xb0, 0x4a, 0x4c, 0x4c, 0x4c, 0x30, 0x7a, 0xf0, 0x32, 0xbb, 0x9e, 0x37, 0x9d, 0xb5,
	0x5b, 0x26, 0x99, 0x99, 0x12, 0xda, 0x49, 0xe4, 0xdb, 0x79, 0xf4, 0xec, 0xc1, 0xe3, 0x7e, 0x16,
	0xd3, 0x76, 0x76, 0x40, 0x67, 0x76, 0x4f, 0xc6, 0xcb, 0x9e, 0xa6, 0xbc, 0xfd, 0x3d, 0x6f, 0x5f,
	0x9e, 0xf7, 0x81, 0xd0, 0xec, 0x36, 0x82, 0x6d, 0xb6, 0xca, 0x28, 0x14, 0x18, 0xa1, 0xcd, 0xe0,
	0x54, 0xc6, 0x66, 0x9d, 0x47, 0xec, 0x52, 0xa5, 0x13, 0xc9, 0x13, 0xfe, 0x6d, 0xa7, 0x22, 0x31,
	0x71, 0xc4, 0xe5, 0x58, 0x8a, 0x6c, 0xbc, 0x15, 0x5f, 0x63, 0xed, 0x0b, 0x13, 0x77, 0xf6, 0xf2,
	0xc1, 0xf8, 0x50, 0xa8, 0xa4, 0xf2, 0x48, 0x94, 0x5f, 0xb9, 0x5f, 0x9e, 0xb7, 0xa7, 0x02, 0x1f,
	0x4a, 0xa5, 0x64, 0x22, 0xf6, 0x94, 0x89, 0x53, 0xa1, 0x0d, 0x4f, 0x37, 0x1e, 0x18, 0xfd, 0x0a,
	0xe0, 0xe3, 0x33, 0xb3, 0x8d, 0x33, 0x79, 0x66, 0xd4, 0x96, 0x4b, 0x71, 0xbe, 0xdb, 0x08, 0x34,
	0x84, 0x5d, 0xad, 0x52, 0x71, 0xa1, 0xdd, 0x0d, 0x06, 0x04, 0xd0, 0x4e, 0x08, 0x6d, 0xc9, 0xb3,
	0xe8, 0x19, 0xec, 0x38, 0x20, 0x52, 0x2a, 0xc1, 0x0d, 0x02, 0x68, 0x3b, 0x6c, 0xdb, 0xc2, 0x7b,
	0xa5, 0x12, 0xf4, 0x02, 0x3a, 0xf4, 0x22, 0xce, 0xcc, 0x6c, 0x8a, 0x9b, 0x04, 0xd0, 0xa3, 0xd0,
	0xe1, 0x9f, 0x6c, 0xa1, 0x6c, 0x9e, 0xfb, 0xfb, 0x80, 0x00, 0x7a, 0xec, 0x9b, 0x7f, 0x71, 0x95,
	0x43, 0xfd, 0x62, 0x8e, 0x8f, 0x08, 0xa0, 0xcd, 0x52, 0xbf, 0x98, 0xff, 0xa1, 0x5f, 0xcc, 0x71,
	0x8b, 0x00, 0x1a, 0xec, 0xf5, 0x8b, 0x79, 0xa9, 0xbf, 0x4a, 0x14, 0x37, 0xf8, 0x21, 0x01, 0xb4,
	0xe1, 0xf5, 0x1f, 0x6c, 0x01, 0xbd, 0x29, 0x66, 0x17, 0x59, 0x9e, 0xe2, 0x36, 0x01, 0xf4, 0x64,
	0xfa, 0x9c, 0xd9, 0xad, 0xb0, 0x8a, 0x11, 0x6c, 0x95, 0xe5, 0xa9, 0xff, 0x67, 0xf6, 0x84, 0x5e,
	0xc3, 0x4e, 0x69, 0x20, 0xee, 0x10, 0x40, 0xbb, 0xd3, 0x01, 0xf3, 0x16, 0xb3, 0x1b, 0x8b, 0xd9,
	0xf9, 0x0d, 0x11, 0xee, 0x61, 0xb4, 0xaa, 0xb1, 0x19, 0x43, 0xd7, 0xe1, 0xe9, 0x2d, 0x8f, 0x87,
	0x35, 0x8b, 0x79, 0x0b, 0x8f, 0xdd, 0xec, 0xa9, 0xd0, 0x9a, 0x4b, 0xa1, 0x71, 0x97, 0x34, 0xef,
	0x6a, 0xd1, 0xb3, 0xf4, 0xe7, 0x02, 0x46, 0x4b, 0x08, 0xcb, 0x89, 0x34, 0xee, 0x39, 0xe9, 0x5d,
	0xf3, 0x1f, 0xd0, 0xa3, 0x97, 0x30, 0x70, 0x16, 0xb4, 0x60, 0x63, 0xf5, 0xaa, 0xff, 0xc0, 0x7d,
	0xa7, 0x7d, 0xe0, 0xbe, 0xb3, 0x7e, 0x63, 0x79, 0xf2, 0xfd, 0x7a, 0x08, 0x7e, 0x5e, 0x0f, 0x5b,
	0x3e, 0x33, 0xa3, 0x1f, 0x01, 0x7c, 0xf4, 0x91, 0xeb, 0xf5, 0xbd, 0x89, 0xd5, 0x69, 0x35, 0x56,
	0x03, 0xbf, 0x96, 0xbf, 0x6c, 0xf8, 0x77, 0xa1, 0x7a, 0x57, 0xb1, 0xb8, 0x88, 0xd4, 0x93, 0xda,
	0x87, 0xc3, 0xca, 0x42, 0x96, 0xf5, 0x71, 0xba, 0x45, 0xfe, 0xff, 0xc2, 0xd4, 0x2b, 0xc2, 0x14,
	0xac, 0xb9, 0x5e, 0x47, 0x2d, 0xd7, 0x6d, 0xf6, 0x3b, 0x00, 0x00, 0xff, 0xff, 0xb7, 0xc2, 0x50,
	0xe6, 0x47, 0x05, 0x00, 0x00,
}
