// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: type.proto

package test

import context "context"
import github_com_gomodule_redigo_redis "github.com/gomodule/redigo/redis"
import github_com_mitchellh_mapstructure "github.com/mitchellh/mapstructure"
import github_com_json_iterator_go "github.com/json-iterator/go"
import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/galaxyobe/protoc-gen-redis/proto"
import _ "github.com/gogo/protobuf/gogoproto"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// new StringStorageType redis controller with redis pool
func (m *StringStorageType) RedisController(pool *github_com_gomodule_redigo_redis.Pool) *StringStorageTypeRedisController {
	return &StringStorageTypeRedisController{
		pool: pool,
		m:    m,
	}
}

// StringStorageType redis controller
type StringStorageTypeRedisController struct {
	pool *github_com_gomodule_redigo_redis.Pool
	m    *StringStorageType
}

// new StringStorageType redis controller with redis pool
func NewStringStorageTypeRedisController(pool *github_com_gomodule_redigo_redis.Pool) *StringStorageTypeRedisController {
	return &StringStorageTypeRedisController{pool: pool, m: new(StringStorageType)}
}

// get StringStorageType
func (r *StringStorageTypeRedisController) StringStorageType() *StringStorageType {
	return r.m
}

// set StringStorageType
func (r *StringStorageTypeRedisController) SetStringStorageType(m *StringStorageType) {
	r.m = m
}

// store StringStorageType to redis string with context and key
func (r *StringStorageTypeRedisController) Store(ctx context.Context, key string) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// marshal StringStorageType to []byte
	data, err := proto.Marshal(r.m)
	if err != nil {
		return err
	}

	// use redis string store StringStorageType data
	_, err = conn.Do("SET", key, data)

	return err
}

// store StringStorageType to redis string with context, key and ttl expire second
func (r *StringStorageTypeRedisController) StoreWithTTL(ctx context.Context, key string, ttl uint64) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// marshal StringStorageType to []byte
	data, err := proto.Marshal(r.m)
	if err != nil {
		return err
	}

	// use redis string store StringStorageType data with expire second
	_, err = conn.Do("SETEX", key, ttl, data)

	return err
}

// load StringStorageType from redis string with context and key
func (r *StringStorageTypeRedisController) Load(ctx context.Context, key string) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// load data from redis string
	data, err := github_com_gomodule_redigo_redis.Bytes(conn.Do("GET", key))
	if err != nil {
		return err
	}

	// unmarshal data to StringStorageType
	return proto.Unmarshal(data, r.m)
}

// new HashStorageType redis controller with redis pool
func (m *HashStorageType) RedisController(pool *github_com_gomodule_redigo_redis.Pool) *HashStorageTypeRedisController {
	return &HashStorageTypeRedisController{
		pool: pool,
		m:    m,
	}
}

// HashStorageType redis controller
type HashStorageTypeRedisController struct {
	pool *github_com_gomodule_redigo_redis.Pool
	m    *HashStorageType
}

// new HashStorageType redis controller with redis pool
func NewHashStorageTypeRedisController(pool *github_com_gomodule_redigo_redis.Pool) *HashStorageTypeRedisController {
	return &HashStorageTypeRedisController{pool: pool, m: new(HashStorageType)}
}

// get HashStorageType
func (r *HashStorageTypeRedisController) HashStorageType() *HashStorageType {
	return r.m
}

// set HashStorageType
func (r *HashStorageTypeRedisController) SetHashStorageType(m *HashStorageType) {
	r.m = m
}

// load HashStorageType from redis hash with context and key
func (r *HashStorageTypeRedisController) Load(ctx context.Context, key string) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// load data from redis hash
	data, err := github_com_gomodule_redigo_redis.ByteSlices(conn.Do("HGETALL", key))
	if err != nil {
		return err
	}

	// parse redis hash field name and value
	structure := make(map[string]interface{})
	for i := 0; i < len(data); i += 2 {
		switch string(data[i]) {
		case "Timestamp":
			// unmarshal Timestamp
			if r.m.Timestamp == nil {
				r.m.Timestamp = new(timestamp.Timestamp)
			}
			if err := proto.Unmarshal(data[i+1], r.m.Timestamp); err != nil {
				return err
			}
		case "HashStorageType":
			// unmarshal HashStorageType
			if r.m.HashStorageType == nil {
				r.m.HashStorageType = new(HashStorageType)
			}
			if err := proto.Unmarshal(data[i+1], r.m.HashStorageType); err != nil {
				return err
			}
		case "SomeMessages":
			// unmarshal SomeMessages
			if r.m.SomeMessages == nil {
				r.m.SomeMessages = make([]*HashStorageType, 0)
			}
			if err := github_com_json_iterator_go.Unmarshal(data[i+1], &r.m.SomeMessages); err != nil {
				return err
			}
		case "Timestamps":
			// unmarshal Timestamps
			if r.m.Timestamps == nil {
				r.m.Timestamps = make([]*timestamp.Timestamp, 0)
			}
			if err := github_com_json_iterator_go.Unmarshal(data[i+1], &r.m.Timestamps); err != nil {
				return err
			}
		default:
			structure[string(data[i])] = string(data[i+1])
		}
	}

	// use mapstructure weak decode structure to HashStorageType
	return github_com_mitchellh_mapstructure.WeakDecode(structure, r.m)
}

// store HashStorageType to redis hash with context and key
func (r *HashStorageTypeRedisController) Store(ctx context.Context, key string) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// make args
	args := make([]interface{}, 0)

	// add redis key
	args = append(args, key)

	// add redis field and value
	args = append(args, "SomeString", r.m.SomeString)
	args = append(args, "SomeBool", r.m.SomeBool)
	args = append(args, "SomeInt32", r.m.SomeInt32)
	args = append(args, "SomeUint32", r.m.SomeUint32)
	args = append(args, "SomeInt64", r.m.SomeInt64)
	args = append(args, "SomeUint64", r.m.SomeUint64)
	args = append(args, "SomeFloat", r.m.SomeFloat)
	args = append(args, "SomeEnum", int32(r.m.SomeEnum))
	// marshal Timestamp
	if r.m.Timestamp != nil {
		Timestamp, TimestampError := proto.Marshal(r.m.Timestamp)
		if TimestampError != nil {
			return TimestampError
		}
		args = append(args, "Timestamp", Timestamp)
	}
	// marshal HashStorageType
	if r.m.HashStorageType != nil {
		HashStorageType, HashStorageTypeError := proto.Marshal(r.m.HashStorageType)
		if HashStorageTypeError != nil {
			return HashStorageTypeError
		}
		args = append(args, "HashStorageType", HashStorageType)
	}
	// marshal SomeMessages
	if r.m.SomeMessages != nil {
		SomeMessages, SomeMessagesError := github_com_json_iterator_go.Marshal(r.m.SomeMessages)
		if SomeMessagesError != nil {
			return SomeMessagesError
		}
		args = append(args, "SomeMessages", SomeMessages)
	}
	// marshal Timestamps
	if r.m.Timestamps != nil {
		Timestamps, TimestampsError := github_com_json_iterator_go.Marshal(r.m.Timestamps)
		if TimestampsError != nil {
			return TimestampsError
		}
		args = append(args, "Timestamps", Timestamps)
	}

	// use redis hash store HashStorageType data
	_, err := conn.Do("HMSET", args...)

	return err
}

// store HashStorageType to redis hash with context, key and ttl expire second
func (r *HashStorageTypeRedisController) StoreWithTTL(ctx context.Context, key string, ttl uint64) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// make args
	args := make([]interface{}, 0)

	// add redis key
	args = append(args, key)

	// add redis field and value
	args = append(args, "SomeString", r.m.SomeString)
	args = append(args, "SomeBool", r.m.SomeBool)
	args = append(args, "SomeInt32", r.m.SomeInt32)
	args = append(args, "SomeUint32", r.m.SomeUint32)
	args = append(args, "SomeInt64", r.m.SomeInt64)
	args = append(args, "SomeUint64", r.m.SomeUint64)
	args = append(args, "SomeFloat", r.m.SomeFloat)
	args = append(args, "SomeEnum", int32(r.m.SomeEnum))
	// marshal Timestamp
	if r.m.Timestamp != nil {
		Timestamp, TimestampError := proto.Marshal(r.m.Timestamp)
		if TimestampError != nil {
			return TimestampError
		}
		args = append(args, "Timestamp", Timestamp)
	}
	// marshal HashStorageType
	if r.m.HashStorageType != nil {
		HashStorageType, HashStorageTypeError := proto.Marshal(r.m.HashStorageType)
		if HashStorageTypeError != nil {
			return HashStorageTypeError
		}
		args = append(args, "HashStorageType", HashStorageType)
	}
	// marshal SomeMessages
	if r.m.SomeMessages != nil {
		SomeMessages, SomeMessagesError := github_com_json_iterator_go.Marshal(r.m.SomeMessages)
		if SomeMessagesError != nil {
			return SomeMessagesError
		}
		args = append(args, "SomeMessages", SomeMessages)
	}
	// marshal Timestamps
	if r.m.Timestamps != nil {
		Timestamps, TimestampsError := github_com_json_iterator_go.Marshal(r.m.Timestamps)
		if TimestampsError != nil {
			return TimestampsError
		}
		args = append(args, "Timestamps", Timestamps)
	}

	// use redis hash store HashStorageType data with expire second
	err := conn.Send("MULTI")
	if err != nil {
		return err
	}
	err = conn.Send("HMSET", args...)
	if err != nil {
		return err
	}
	err = conn.Send("EXPIRE", key, ttl)
	if err != nil {
		return err
	}
	_, err = conn.Do("EXEC")

	return err
}

// get HashStorageType SomeString field value with key
func (r *HashStorageTypeRedisController) GetSomeString(key string) (someString string, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeString field
	if value, err := github_com_gomodule_redigo_redis.String(conn.Do("HGET", key, "SomeString")); err != nil {
		return someString, err
	} else {
		r.m.SomeString = value
	}

	return r.m.SomeString, nil
}

// set HashStorageType SomeString field with key and SomeString
func (r *HashStorageTypeRedisController) SetSomeString(key string, someString string) (err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// set SomeString field
	r.m.SomeString = someString
	_, err = conn.Do("HSET", key, "SomeString", someString)

	return
}

// get HashStorageType SomeBool field value with key
func (r *HashStorageTypeRedisController) GetSomeBool(key string) (someBool bool, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeBool field
	if value, err := github_com_gomodule_redigo_redis.Bool(conn.Do("HGET", key, "SomeBool")); err != nil {
		return someBool, err
	} else {
		r.m.SomeBool = value
	}

	return r.m.SomeBool, nil
}

// set HashStorageType SomeBool field with key and SomeBool
func (r *HashStorageTypeRedisController) SetSomeBool(key string, someBool bool) (err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// set SomeBool field
	r.m.SomeBool = someBool
	_, err = conn.Do("HSET", key, "SomeBool", someBool)

	return
}

// get HashStorageType SomeInt32 field value with key
func (r *HashStorageTypeRedisController) GetSomeInt32(key string) (someInt32 int32, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeInt32 field
	if value, err := github_com_gomodule_redigo_redis.Int64(conn.Do("HGET", key, "SomeInt32")); err != nil {
		return someInt32, err
	} else {
		r.m.SomeInt32 = int32(value)
	}

	return r.m.SomeInt32, nil
}

// set HashStorageType SomeInt32 field with key and SomeInt32
func (r *HashStorageTypeRedisController) SetSomeInt32(key string, someInt32 int32) (err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// set SomeInt32 field
	r.m.SomeInt32 = someInt32
	_, err = conn.Do("HSET", key, "SomeInt32", someInt32)

	return
}

// get HashStorageType SomeUint32 field value with key
func (r *HashStorageTypeRedisController) GetSomeUint32(key string) (someUint32 uint32, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeUint32 field
	if value, err := github_com_gomodule_redigo_redis.Uint64(conn.Do("HGET", key, "SomeUint32")); err != nil {
		return someUint32, err
	} else {
		r.m.SomeUint32 = uint32(value)
	}

	return r.m.SomeUint32, nil
}

// set HashStorageType SomeUint32 field with key and SomeUint32
func (r *HashStorageTypeRedisController) SetSomeUint32(key string, someUint32 uint32) (err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// set SomeUint32 field
	r.m.SomeUint32 = someUint32
	_, err = conn.Do("HSET", key, "SomeUint32", someUint32)

	return
}

// get HashStorageType SomeInt64 field value with key
func (r *HashStorageTypeRedisController) GetSomeInt64(key string) (someInt64 int64, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeInt64 field
	if value, err := github_com_gomodule_redigo_redis.Int64(conn.Do("HGET", key, "SomeInt64")); err != nil {
		return someInt64, err
	} else {
		r.m.SomeInt64 = value
	}

	return r.m.SomeInt64, nil
}

// set HashStorageType SomeInt64 field with key and SomeInt64
func (r *HashStorageTypeRedisController) SetSomeInt64(key string, someInt64 int64) (err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// set SomeInt64 field
	r.m.SomeInt64 = someInt64
	_, err = conn.Do("HSET", key, "SomeInt64", someInt64)

	return
}

// get HashStorageType SomeUint64 field value with key
func (r *HashStorageTypeRedisController) GetSomeUint64(key string) (someUint64 uint64, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeUint64 field
	if value, err := github_com_gomodule_redigo_redis.Uint64(conn.Do("HGET", key, "SomeUint64")); err != nil {
		return someUint64, err
	} else {
		r.m.SomeUint64 = value
	}

	return r.m.SomeUint64, nil
}

// set HashStorageType SomeUint64 field with key and SomeUint64
func (r *HashStorageTypeRedisController) SetSomeUint64(key string, someUint64 uint64) (err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// set SomeUint64 field
	r.m.SomeUint64 = someUint64
	_, err = conn.Do("HSET", key, "SomeUint64", someUint64)

	return
}

// get HashStorageType SomeFloat field value with key
func (r *HashStorageTypeRedisController) GetSomeFloat(key string) (someFloat float32, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeFloat field
	if value, err := github_com_gomodule_redigo_redis.Float64(conn.Do("HGET", key, "SomeFloat")); err != nil {
		return someFloat, err
	} else {
		r.m.SomeFloat = float32(value)
	}

	return r.m.SomeFloat, nil
}

// set HashStorageType SomeFloat field with key and SomeFloat
func (r *HashStorageTypeRedisController) SetSomeFloat(key string, someFloat float32) (err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// set SomeFloat field
	r.m.SomeFloat = someFloat
	_, err = conn.Do("HSET", key, "SomeFloat", someFloat)

	return
}

// get HashStorageType SomeEnum field value with key
func (r *HashStorageTypeRedisController) GetSomeEnum(key string) (someEnum HashStorageType_Enum, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeEnum field
	if value, err := github_com_gomodule_redigo_redis.Int64(conn.Do("HGET", key, "SomeEnum")); err != nil {
		return someEnum, err
	} else {
		r.m.SomeEnum = HashStorageType_Enum(value)
	}

	return r.m.SomeEnum, nil
}

// set HashStorageType SomeEnum field with key and SomeEnum
func (r *HashStorageTypeRedisController) SetSomeEnum(key string, someEnum HashStorageType_Enum) (err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// set SomeEnum field
	r.m.SomeEnum = someEnum
	_, err = conn.Do("HSET", key, "SomeEnum", int32(someEnum))

	return
}

// get HashStorageType Timestamp field value with key
func (r *HashStorageTypeRedisController) GetTimestamp(key string) (ret *timestamp.Timestamp, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get Timestamp field
	if value, err := github_com_gomodule_redigo_redis.Bytes(conn.Do("HGET", key, "Timestamp")); err != nil {
		return ret, err
	} else {
		// unmarshal Timestamp
		if r.m.Timestamp == nil {
			r.m.Timestamp = new(timestamp.Timestamp)
		}
		if err = proto.Unmarshal(value, r.m.Timestamp); err != nil {
			return ret, err
		}
	}

	return r.m.Timestamp, nil
}

// set HashStorageType Timestamp field with key and Timestamp
func (r *HashStorageTypeRedisController) SetTimestamp(key string, timestamp *timestamp.Timestamp) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// marshal Timestamp
	r.m.Timestamp = timestamp
	if data, err := proto.Marshal(r.m.Timestamp); err != nil {
		return err
	} else {
		// set Timestamp field
		_, err = conn.Do("HSET", key, "Timestamp", data)
		return err
	}

	return nil
}

// get HashStorageType HashStorageType field value with key
func (r *HashStorageTypeRedisController) GetHashStorageType(key string) (ret *HashStorageType, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get HashStorageType field
	if value, err := github_com_gomodule_redigo_redis.Bytes(conn.Do("HGET", key, "HashStorageType")); err != nil {
		return ret, err
	} else {
		// unmarshal HashStorageType
		if r.m.HashStorageType == nil {
			r.m.HashStorageType = new(HashStorageType)
		}
		if err = proto.Unmarshal(value, r.m.HashStorageType); err != nil {
			return ret, err
		}
	}

	return r.m.HashStorageType, nil
}

// set HashStorageType HashStorageType field with key and HashStorageType
func (r *HashStorageTypeRedisController) SetHashStorageTypeField(key string, HashStorageType *HashStorageType) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// marshal HashStorageType
	r.m.HashStorageType = HashStorageType
	if data, err := proto.Marshal(r.m.HashStorageType); err != nil {
		return err
	} else {
		// set HashStorageType field
		_, err = conn.Do("HSET", key, "HashStorageType", data)
		return err
	}

	return nil
}

// get HashStorageType SomeMessages field value with key
func (r *HashStorageTypeRedisController) GetSomeMessages(key string) (ret []*HashStorageType, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get SomeMessages field
	if value, err := github_com_gomodule_redigo_redis.Bytes(conn.Do("HGET", key, "SomeMessages")); err != nil {
		return ret, err
	} else {
		// unmarshal SomeMessages
		if r.m.SomeMessages == nil {
			r.m.SomeMessages = make([]*HashStorageType, 0)
		}
		if err = github_com_json_iterator_go.Unmarshal(value, r.m.SomeMessages); err != nil {
			return ret, err
		}
	}

	return r.m.SomeMessages, nil
}

// set HashStorageType SomeMessages field with key and SomeMessages
func (r *HashStorageTypeRedisController) SetSomeMessages(key string, someMessages []*HashStorageType) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// marshal SomeMessages
	r.m.SomeMessages = someMessages
	if data, err := github_com_json_iterator_go.Marshal(r.m.SomeMessages); err != nil {
		return err
	} else {
		// set SomeMessages field
		_, err = conn.Do("HSET", key, "SomeMessages", data)
		return err
	}

	return nil
}

// get HashStorageType Timestamps field value with key
func (r *HashStorageTypeRedisController) GetTimestamps(key string) (ret []*timestamp.Timestamp, err error) {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// get Timestamps field
	if value, err := github_com_gomodule_redigo_redis.Bytes(conn.Do("HGET", key, "Timestamps")); err != nil {
		return ret, err
	} else {
		// unmarshal Timestamps
		if r.m.Timestamps == nil {
			r.m.Timestamps = make([]*timestamp.Timestamp, 0)
		}
		if err = github_com_json_iterator_go.Unmarshal(value, r.m.Timestamps); err != nil {
			return ret, err
		}
	}

	return r.m.Timestamps, nil
}

// set HashStorageType Timestamps field with key and Timestamps
func (r *HashStorageTypeRedisController) SetTimestamps(key string, timestamps []*timestamp.Timestamp) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// marshal Timestamps
	r.m.Timestamps = timestamps
	if data, err := github_com_json_iterator_go.Marshal(r.m.Timestamps); err != nil {
		return err
	} else {
		// set Timestamps field
		_, err = conn.Do("HSET", key, "Timestamps", data)
		return err
	}

	return nil
}
