// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hash_getter_setter.proto

package test

import (
	fmt "fmt"
	_ "github.com/galaxyobe/protoc-gen-redis/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HashGetterAndSetterType_Enum int32

const (
	HashGetterAndSetterType_E1 HashGetterAndSetterType_Enum = 0
	HashGetterAndSetterType_E2 HashGetterAndSetterType_Enum = 1
)

var HashGetterAndSetterType_Enum_name = map[int32]string{
	0: "E1",
	1: "E2",
}

var HashGetterAndSetterType_Enum_value = map[string]int32{
	"E1": 0,
	"E2": 1,
}

func (x HashGetterAndSetterType_Enum) String() string {
	return proto.EnumName(HashGetterAndSetterType_Enum_name, int32(x))
}

func (HashGetterAndSetterType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_986096eaff9196ff, []int{0, 0}
}

type HashGetterAndSetterType struct {
	SomeString           string                       `protobuf:"bytes,1,opt,name=some_string,json=someString,proto3" json:"some_string,omitempty"`
	SomeBool             bool                         `protobuf:"varint,2,opt,name=some_bool,json=someBool,proto3" json:"some_bool,omitempty"`
	SomeInt32            int32                        `protobuf:"varint,3,opt,name=some_int32,json=someInt32,proto3" json:"some_int32,omitempty"`
	SomeUint32           uint32                       `protobuf:"varint,4,opt,name=some_uint32,json=someUint32,proto3" json:"some_uint32,omitempty"`
	SomeInt64            int64                        `protobuf:"varint,5,opt,name=some_int64,json=someInt64,proto3" json:"some_int64,omitempty"`
	SomeUint64           uint64                       `protobuf:"varint,6,opt,name=some_uint64,json=someUint64,proto3" json:"some_uint64,omitempty"`
	SomeFloat            float32                      `protobuf:"fixed32,7,opt,name=some_float,json=someFloat,proto3" json:"some_float,omitempty"`
	SomeEnum             HashGetterAndSetterType_Enum `protobuf:"varint,8,opt,name=some_enum,json=someEnum,proto3,enum=test.HashGetterAndSetterType_Enum" json:"some_enum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                     `json:"-"`
	XXX_unrecognized     []byte                       `json:"-"`
	XXX_sizecache        int32                        `json:"-"`
}

func (m *HashGetterAndSetterType) Reset()         { *m = HashGetterAndSetterType{} }
func (m *HashGetterAndSetterType) String() string { return proto.CompactTextString(m) }
func (*HashGetterAndSetterType) ProtoMessage()    {}
func (*HashGetterAndSetterType) Descriptor() ([]byte, []int) {
	return fileDescriptor_986096eaff9196ff, []int{0}
}

func (m *HashGetterAndSetterType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashGetterAndSetterType.Unmarshal(m, b)
}
func (m *HashGetterAndSetterType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashGetterAndSetterType.Marshal(b, m, deterministic)
}
func (m *HashGetterAndSetterType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashGetterAndSetterType.Merge(m, src)
}
func (m *HashGetterAndSetterType) XXX_Size() int {
	return xxx_messageInfo_HashGetterAndSetterType.Size(m)
}
func (m *HashGetterAndSetterType) XXX_DiscardUnknown() {
	xxx_messageInfo_HashGetterAndSetterType.DiscardUnknown(m)
}

var xxx_messageInfo_HashGetterAndSetterType proto.InternalMessageInfo

func (m *HashGetterAndSetterType) GetSomeString() string {
	if m != nil {
		return m.SomeString
	}
	return ""
}

func (m *HashGetterAndSetterType) GetSomeBool() bool {
	if m != nil {
		return m.SomeBool
	}
	return false
}

func (m *HashGetterAndSetterType) GetSomeInt32() int32 {
	if m != nil {
		return m.SomeInt32
	}
	return 0
}

func (m *HashGetterAndSetterType) GetSomeUint32() uint32 {
	if m != nil {
		return m.SomeUint32
	}
	return 0
}

func (m *HashGetterAndSetterType) GetSomeInt64() int64 {
	if m != nil {
		return m.SomeInt64
	}
	return 0
}

func (m *HashGetterAndSetterType) GetSomeUint64() uint64 {
	if m != nil {
		return m.SomeUint64
	}
	return 0
}

func (m *HashGetterAndSetterType) GetSomeFloat() float32 {
	if m != nil {
		return m.SomeFloat
	}
	return 0
}

func (m *HashGetterAndSetterType) GetSomeEnum() HashGetterAndSetterType_Enum {
	if m != nil {
		return m.SomeEnum
	}
	return HashGetterAndSetterType_E1
}

func init() {
	proto.RegisterEnum("test.HashGetterAndSetterType_Enum", HashGetterAndSetterType_Enum_name, HashGetterAndSetterType_Enum_value)
	proto.RegisterType((*HashGetterAndSetterType)(nil), "test.HashGetterAndSetterType")
}

func init() { proto.RegisterFile("hash_getter_setter.proto", fileDescriptor_986096eaff9196ff) }

var fileDescriptor_986096eaff9196ff = []byte{
	// 350 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x91, 0xc1, 0x4e, 0xf2, 0x40,
	0x10, 0xc7, 0xd9, 0x52, 0xf8, 0xca, 0x7e, 0xd1, 0x90, 0xc6, 0xe8, 0x06, 0x63, 0xba, 0xe1, 0xb4,
	0x17, 0x4a, 0x84, 0xa6, 0x26, 0xde, 0x24, 0x41, 0xe5, 0x0a, 0x7a, 0x6e, 0x5a, 0x58, 0xda, 0x26,
	0x6d, 0x97, 0x74, 0xb7, 0x89, 0xbc, 0x9d, 0xcf, 0xe0, 0x03, 0x34, 0x1e, 0x38, 0x78, 0xd3, 0xa3,
	0x47, 0xb3, 0xbb, 0x06, 0xf1, 0xe0, 0x69, 0xa6, 0xbf, 0xfe, 0x7f, 0x93, 0xe9, 0x14, 0xa2, 0x24,
	0xe4, 0x49, 0x10, 0x53, 0x21, 0x68, 0x19, 0x70, 0x55, 0xdc, 0x4d, 0xc9, 0x04, 0xb3, 0x4d, 0x41,
	0xb9, 0xe8, 0x5d, 0xc5, 0xa9, 0x48, 0xaa, 0xc8, 0x5d, 0xb2, 0x7c, 0x18, 0x87, 0x59, 0xf8, 0xb4,
	0x65, 0x11, 0x1d, 0xaa, 0xc4, 0x72, 0x10, 0xd3, 0x62, 0x50, 0xd2, 0x55, 0xca, 0x35, 0x18, 0xaa,
	0x5e, 0xeb, 0xbd, 0xc1, 0xa1, 0xc8, 0x62, 0xa6, 0x23, 0x51, 0xb5, 0x56, 0x4f, 0x3a, 0x2f, 0x3b,
	0x1d, 0xef, 0xbf, 0x1b, 0xf0, 0xec, 0x3e, 0xe4, 0xc9, 0x9d, 0x5a, 0xe1, 0xa6, 0x58, 0x2d, 0x54,
	0xf3, 0xb0, 0xdd, 0x50, 0xdb, 0x81, 0xff, 0x39, 0xcb, 0x69, 0xc0, 0x45, 0x99, 0x16, 0x31, 0x02,
	0x18, 0x90, 0xce, 0x1c, 0x4a, 0xb4, 0x50, 0xc4, 0x3e, 0x87, 0x1d, 0x15, 0x88, 0x18, 0xcb, 0x90,
	0x81, 0x01, 0xb1, 0xe6, 0x96, 0x04, 0x13, 0xc6, 0x32, 0xfb, 0x02, 0xaa, 0x68, 0x90, 0x16, 0x62,
	0x3c, 0x42, 0x4d, 0x0c, 0x48, 0x6b, 0xae, 0xe2, 0x33, 0x09, 0xf6, 0xc3, 0x2b, 0xfd, 0xde, 0xc4,
	0x80, 0x1c, 0xe9, 0xe1, 0x8f, 0x8a, 0x1c, 0xfa, 0xbe, 0x87, 0x5a, 0x18, 0x90, 0xe6, 0xde, 0xf7,
	0xbd, 0x5f, 0xbe, 0xef, 0xa1, 0x36, 0x06, 0xc4, 0xfc, 0xf1, 0x7d, 0x6f, 0xef, 0xaf, 0x33, 0x16,
	0x0a, 0xf4, 0x0f, 0x03, 0x62, 0x68, 0xff, 0x56, 0x02, 0x7b, 0xf6, 0xbd, 0x3b, 0x2d, 0xaa, 0x1c,
	0x59, 0x18, 0x90, 0xe3, 0x51, 0xdf, 0x95, 0xa7, 0x77, 0xff, 0x38, 0x87, 0x3b, 0x2d, 0xaa, 0x7c,
	0x62, 0x7d, 0xec, 0x1c, 0xf0, 0xb9, 0x73, 0x1a, 0xfa, 0x4b, 0x25, 0xeb, 0x9f, 0x42, 0x53, 0x56,
	0xbb, 0x0d, 0x8d, 0xe9, 0x65, 0xb7, 0xa1, 0xea, 0xa8, 0x0b, 0xae, 0x4f, 0x9e, 0x6b, 0x07, 0xbc,
	0xd4, 0x8e, 0x29, 0xff, 0xf5, 0x6b, 0xed, 0x34, 0xde, 0x6a, 0x07, 0x44, 0x6d, 0x75, 0xf8, 0xf1,
	0x57, 0x00, 0x00, 0x00, 0xff, 0xff, 0x5b, 0xb1, 0x3f, 0xff, 0x02, 0x02, 0x00, 0x00,
}
