// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hash_type.proto

package test

import (
	fmt "fmt"
	_ "github.com/galaxyobe/protoc-gen-redis/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type HashStorageType struct {
	SomeString           string   `protobuf:"bytes,1,opt,name=some_string,json=someString,proto3" json:"some_string,omitempty"`
	SomeBool             bool     `protobuf:"varint,2,opt,name=some_bool,json=someBool,proto3" json:"some_bool,omitempty"`
	SomeInt32            int32    `protobuf:"varint,3,opt,name=some_int32,json=someInt32,proto3" json:"some_int32,omitempty"`
	SomeUint32           uint32   `protobuf:"varint,4,opt,name=some_uint32,json=someUint32,proto3" json:"some_uint32,omitempty"`
	SomeInt64            int64    `protobuf:"varint,5,opt,name=some_int64,json=someInt64,proto3" json:"some_int64,omitempty"`
	SomeUint64           uint64   `protobuf:"varint,6,opt,name=some_uint64,json=someUint64,proto3" json:"some_uint64,omitempty"`
	SomeFloat            float32  `protobuf:"fixed32,7,opt,name=some_float,json=someFloat,proto3" json:"some_float,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HashStorageType) Reset()         { *m = HashStorageType{} }
func (m *HashStorageType) String() string { return proto.CompactTextString(m) }
func (*HashStorageType) ProtoMessage()    {}
func (*HashStorageType) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cd8e24a8ed3f5, []int{0}
}

func (m *HashStorageType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashStorageType.Unmarshal(m, b)
}
func (m *HashStorageType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashStorageType.Marshal(b, m, deterministic)
}
func (m *HashStorageType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashStorageType.Merge(m, src)
}
func (m *HashStorageType) XXX_Size() int {
	return xxx_messageInfo_HashStorageType.Size(m)
}
func (m *HashStorageType) XXX_DiscardUnknown() {
	xxx_messageInfo_HashStorageType.DiscardUnknown(m)
}

var xxx_messageInfo_HashStorageType proto.InternalMessageInfo

func (m *HashStorageType) GetSomeString() string {
	if m != nil {
		return m.SomeString
	}
	return ""
}

func (m *HashStorageType) GetSomeBool() bool {
	if m != nil {
		return m.SomeBool
	}
	return false
}

func (m *HashStorageType) GetSomeInt32() int32 {
	if m != nil {
		return m.SomeInt32
	}
	return 0
}

func (m *HashStorageType) GetSomeUint32() uint32 {
	if m != nil {
		return m.SomeUint32
	}
	return 0
}

func (m *HashStorageType) GetSomeInt64() int64 {
	if m != nil {
		return m.SomeInt64
	}
	return 0
}

func (m *HashStorageType) GetSomeUint64() uint64 {
	if m != nil {
		return m.SomeUint64
	}
	return 0
}

func (m *HashStorageType) GetSomeFloat() float32 {
	if m != nil {
		return m.SomeFloat
	}
	return 0
}

type HashStorageType2 struct {
	SomeString           string           `protobuf:"bytes,1,opt,name=some_string,json=someString,proto3" json:"some_string,omitempty"`
	SomeBool             bool             `protobuf:"varint,2,opt,name=some_bool,json=someBool,proto3" json:"some_bool,omitempty"`
	SomeInt32            int32            `protobuf:"varint,3,opt,name=some_int32,json=someInt32,proto3" json:"some_int32,omitempty"`
	SomeUint32           uint32           `protobuf:"varint,4,opt,name=some_uint32,json=someUint32,proto3" json:"some_uint32,omitempty"`
	SomeInt64            int64            `protobuf:"varint,5,opt,name=some_int64,json=someInt64,proto3" json:"some_int64,omitempty"`
	SomeUint64           uint64           `protobuf:"varint,6,opt,name=some_uint64,json=someUint64,proto3" json:"some_uint64,omitempty"`
	SomeFloat            float32          `protobuf:"fixed32,7,opt,name=some_float,json=someFloat,proto3" json:"some_float,omitempty"`
	SomeMessage          *HashStorageType `protobuf:"bytes,8,opt,name=some_message,json=someMessage,proto3" json:"some_message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *HashStorageType2) Reset()         { *m = HashStorageType2{} }
func (m *HashStorageType2) String() string { return proto.CompactTextString(m) }
func (*HashStorageType2) ProtoMessage()    {}
func (*HashStorageType2) Descriptor() ([]byte, []int) {
	return fileDescriptor_f52cd8e24a8ed3f5, []int{1}
}

func (m *HashStorageType2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashStorageType2.Unmarshal(m, b)
}
func (m *HashStorageType2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashStorageType2.Marshal(b, m, deterministic)
}
func (m *HashStorageType2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashStorageType2.Merge(m, src)
}
func (m *HashStorageType2) XXX_Size() int {
	return xxx_messageInfo_HashStorageType2.Size(m)
}
func (m *HashStorageType2) XXX_DiscardUnknown() {
	xxx_messageInfo_HashStorageType2.DiscardUnknown(m)
}

var xxx_messageInfo_HashStorageType2 proto.InternalMessageInfo

func (m *HashStorageType2) GetSomeString() string {
	if m != nil {
		return m.SomeString
	}
	return ""
}

func (m *HashStorageType2) GetSomeBool() bool {
	if m != nil {
		return m.SomeBool
	}
	return false
}

func (m *HashStorageType2) GetSomeInt32() int32 {
	if m != nil {
		return m.SomeInt32
	}
	return 0
}

func (m *HashStorageType2) GetSomeUint32() uint32 {
	if m != nil {
		return m.SomeUint32
	}
	return 0
}

func (m *HashStorageType2) GetSomeInt64() int64 {
	if m != nil {
		return m.SomeInt64
	}
	return 0
}

func (m *HashStorageType2) GetSomeUint64() uint64 {
	if m != nil {
		return m.SomeUint64
	}
	return 0
}

func (m *HashStorageType2) GetSomeFloat() float32 {
	if m != nil {
		return m.SomeFloat
	}
	return 0
}

func (m *HashStorageType2) GetSomeMessage() *HashStorageType {
	if m != nil {
		return m.SomeMessage
	}
	return nil
}

func init() {
	proto.RegisterType((*HashStorageType)(nil), "test.HashStorageType")
	proto.RegisterType((*HashStorageType2)(nil), "test.HashStorageType2")
}

func init() { proto.RegisterFile("hash_type.proto", fileDescriptor_f52cd8e24a8ed3f5) }

var fileDescriptor_f52cd8e24a8ed3f5 = []byte{
	// 323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x92, 0xc1, 0x6a, 0xf2, 0x40,
	0x10, 0xc7, 0x59, 0x8d, 0x7e, 0xba, 0xfa, 0x61, 0x09, 0x14, 0x16, 0x4b, 0x71, 0xf1, 0xb4, 0x17,
	0x23, 0x68, 0x48, 0x4b, 0x8f, 0x3d, 0x94, 0xf6, 0xd0, 0x4b, 0x6c, 0xcf, 0xb2, 0xb1, 0xeb, 0x26,
	0x10, 0x9d, 0x90, 0xdd, 0x40, 0xf3, 0x64, 0xbd, 0xf6, 0x19, 0xfa, 0x00, 0x3e, 0x49, 0x0f, 0x65,
	0x77, 0x21, 0x55, 0x1f, 0xa1, 0xb7, 0xcd, 0x7f, 0x7e, 0xbf, 0x09, 0x33, 0x0c, 0x1e, 0xa5, 0x5c,
	0xa5, 0x6b, 0x5d, 0x17, 0x22, 0x28, 0x4a, 0xd0, 0xe0, 0x7b, 0x5a, 0x28, 0x3d, 0xbe, 0x91, 0x99,
	0x4e, 0xab, 0x24, 0xd8, 0xc0, 0x6e, 0x2e, 0x79, 0xce, 0xdf, 0x6b, 0x48, 0xc4, 0xdc, 0x12, 0x9b,
	0x99, 0x14, 0xfb, 0x59, 0x29, 0xde, 0x32, 0xe5, 0x82, 0xb9, 0x7d, 0x3b, 0x7d, 0x3c, 0x3b, 0x16,
	0x41, 0x82, 0x43, 0x92, 0x6a, 0x6b, 0xbf, 0x1c, 0x6f, 0x5e, 0x0e, 0x9f, 0x7e, 0x23, 0x3c, 0x7a,
	0xe4, 0x2a, 0x5d, 0x69, 0x28, 0xb9, 0x14, 0x2f, 0x75, 0x21, 0xfc, 0x09, 0x1e, 0x28, 0xd8, 0x89,
	0xb5, 0xd2, 0x65, 0xb6, 0x97, 0x04, 0x51, 0xc4, 0xfa, 0x31, 0x36, 0xd1, 0xca, 0x26, 0xfe, 0x15,
	0xee, 0x5b, 0x20, 0x01, 0xc8, 0x49, 0x8b, 0x22, 0xd6, 0x8b, 0x7b, 0x26, 0xb8, 0x07, 0xc8, 0xfd,
	0x6b, 0x6c, 0xd1, 0x75, 0xb6, 0xd7, 0xcb, 0x05, 0x69, 0x53, 0xc4, 0x3a, 0xb1, 0xc5, 0x9f, 0x4c,
	0xd0, 0x34, 0xaf, 0x5c, 0xdd, 0xa3, 0x88, 0xfd, 0x77, 0xcd, 0x5f, 0x6d, 0x72, 0xec, 0x47, 0x21,
	0xe9, 0x50, 0xc4, 0xda, 0x8d, 0x1f, 0x85, 0x27, 0x7e, 0x14, 0x92, 0x2e, 0x45, 0xcc, 0xfb, 0xf5,
	0xa3, 0xb0, 0xf1, 0xb7, 0x39, 0x70, 0x4d, 0xfe, 0x51, 0xc4, 0x5a, 0xce, 0x7f, 0x30, 0xc1, 0xdd,
	0xf0, 0xf3, 0x30, 0x41, 0x5f, 0x87, 0x89, 0x67, 0xf6, 0x3e, 0xfd, 0x68, 0xe1, 0x8b, 0xb3, 0xf1,
	0x17, 0x7f, 0x7a, 0x7e, 0xff, 0x16, 0x0f, 0x6d, 0x79, 0x27, 0x94, 0xe2, 0x52, 0x90, 0x1e, 0x45,
	0x6c, 0xb0, 0xb8, 0x0c, 0xcc, 0xd5, 0x05, 0x67, 0xab, 0x88, 0xed, 0xaf, 0x9e, 0x1d, 0x79, 0xba,
	0xb9, 0xa4, 0x6b, 0xef, 0x67, 0xf9, 0x13, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x59, 0xe9, 0x5c, 0xc0,
	0x02, 0x00, 0x00,
}
