// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto_codec.proto

package test

import (
	fmt "fmt"
	_ "github.com/galaxyobe/protoc-gen-redis/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StringProtoCodec struct {
	SomeString           string            `protobuf:"bytes,1,opt,name=some_string,json=someString,proto3" json:"some_string,omitempty"`
	SomeBool             bool              `protobuf:"varint,2,opt,name=some_bool,json=someBool,proto3" json:"some_bool,omitempty"`
	SomeInt32            int32             `protobuf:"varint,3,opt,name=some_int32,json=someInt32,proto3" json:"some_int32,omitempty"`
	SomeUint32           uint32            `protobuf:"varint,4,opt,name=some_uint32,json=someUint32,proto3" json:"some_uint32,omitempty"`
	SomeInt64            int64             `protobuf:"varint,5,opt,name=some_int64,json=someInt64,proto3" json:"some_int64,omitempty"`
	SomeUint64           uint64            `protobuf:"varint,6,opt,name=some_uint64,json=someUint64,proto3" json:"some_uint64,omitempty"`
	SomeFloat            float32           `protobuf:"fixed32,7,opt,name=some_float,json=someFloat,proto3" json:"some_float,omitempty"`
	StringProtoCodec     *StringProtoCodec `protobuf:"bytes,8,opt,name=StringProtoCodec,proto3" json:"StringProtoCodec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StringProtoCodec) Reset()         { *m = StringProtoCodec{} }
func (m *StringProtoCodec) String() string { return proto.CompactTextString(m) }
func (*StringProtoCodec) ProtoMessage()    {}
func (*StringProtoCodec) Descriptor() ([]byte, []int) {
	return fileDescriptor_55a7f4844f88f049, []int{0}
}

func (m *StringProtoCodec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringProtoCodec.Unmarshal(m, b)
}
func (m *StringProtoCodec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringProtoCodec.Marshal(b, m, deterministic)
}
func (m *StringProtoCodec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringProtoCodec.Merge(m, src)
}
func (m *StringProtoCodec) XXX_Size() int {
	return xxx_messageInfo_StringProtoCodec.Size(m)
}
func (m *StringProtoCodec) XXX_DiscardUnknown() {
	xxx_messageInfo_StringProtoCodec.DiscardUnknown(m)
}

var xxx_messageInfo_StringProtoCodec proto.InternalMessageInfo

func (m *StringProtoCodec) GetSomeString() string {
	if m != nil {
		return m.SomeString
	}
	return ""
}

func (m *StringProtoCodec) GetSomeBool() bool {
	if m != nil {
		return m.SomeBool
	}
	return false
}

func (m *StringProtoCodec) GetSomeInt32() int32 {
	if m != nil {
		return m.SomeInt32
	}
	return 0
}

func (m *StringProtoCodec) GetSomeUint32() uint32 {
	if m != nil {
		return m.SomeUint32
	}
	return 0
}

func (m *StringProtoCodec) GetSomeInt64() int64 {
	if m != nil {
		return m.SomeInt64
	}
	return 0
}

func (m *StringProtoCodec) GetSomeUint64() uint64 {
	if m != nil {
		return m.SomeUint64
	}
	return 0
}

func (m *StringProtoCodec) GetSomeFloat() float32 {
	if m != nil {
		return m.SomeFloat
	}
	return 0
}

func (m *StringProtoCodec) GetStringProtoCodec() *StringProtoCodec {
	if m != nil {
		return m.StringProtoCodec
	}
	return nil
}

type HashProtoCodec struct {
	SomeString           string          `protobuf:"bytes,1,opt,name=some_string,json=someString,proto3" json:"some_string,omitempty"`
	SomeBool             bool            `protobuf:"varint,2,opt,name=some_bool,json=someBool,proto3" json:"some_bool,omitempty"`
	SomeInt32            int32           `protobuf:"varint,3,opt,name=some_int32,json=someInt32,proto3" json:"some_int32,omitempty"`
	SomeUint32           uint32          `protobuf:"varint,4,opt,name=some_uint32,json=someUint32,proto3" json:"some_uint32,omitempty"`
	SomeInt64            int64           `protobuf:"varint,5,opt,name=some_int64,json=someInt64,proto3" json:"some_int64,omitempty"`
	SomeUint64           uint64          `protobuf:"varint,6,opt,name=some_uint64,json=someUint64,proto3" json:"some_uint64,omitempty"`
	SomeFloat            float32         `protobuf:"fixed32,7,opt,name=some_float,json=someFloat,proto3" json:"some_float,omitempty"`
	HashProtoCodec       *HashProtoCodec `protobuf:"bytes,8,opt,name=HashProtoCodec,proto3" json:"HashProtoCodec,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *HashProtoCodec) Reset()         { *m = HashProtoCodec{} }
func (m *HashProtoCodec) String() string { return proto.CompactTextString(m) }
func (*HashProtoCodec) ProtoMessage()    {}
func (*HashProtoCodec) Descriptor() ([]byte, []int) {
	return fileDescriptor_55a7f4844f88f049, []int{1}
}

func (m *HashProtoCodec) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HashProtoCodec.Unmarshal(m, b)
}
func (m *HashProtoCodec) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HashProtoCodec.Marshal(b, m, deterministic)
}
func (m *HashProtoCodec) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HashProtoCodec.Merge(m, src)
}
func (m *HashProtoCodec) XXX_Size() int {
	return xxx_messageInfo_HashProtoCodec.Size(m)
}
func (m *HashProtoCodec) XXX_DiscardUnknown() {
	xxx_messageInfo_HashProtoCodec.DiscardUnknown(m)
}

var xxx_messageInfo_HashProtoCodec proto.InternalMessageInfo

func (m *HashProtoCodec) GetSomeString() string {
	if m != nil {
		return m.SomeString
	}
	return ""
}

func (m *HashProtoCodec) GetSomeBool() bool {
	if m != nil {
		return m.SomeBool
	}
	return false
}

func (m *HashProtoCodec) GetSomeInt32() int32 {
	if m != nil {
		return m.SomeInt32
	}
	return 0
}

func (m *HashProtoCodec) GetSomeUint32() uint32 {
	if m != nil {
		return m.SomeUint32
	}
	return 0
}

func (m *HashProtoCodec) GetSomeInt64() int64 {
	if m != nil {
		return m.SomeInt64
	}
	return 0
}

func (m *HashProtoCodec) GetSomeUint64() uint64 {
	if m != nil {
		return m.SomeUint64
	}
	return 0
}

func (m *HashProtoCodec) GetSomeFloat() float32 {
	if m != nil {
		return m.SomeFloat
	}
	return 0
}

func (m *HashProtoCodec) GetHashProtoCodec() *HashProtoCodec {
	if m != nil {
		return m.HashProtoCodec
	}
	return nil
}

func init() {
	proto.RegisterType((*StringProtoCodec)(nil), "test.StringProtoCodec")
	proto.RegisterType((*HashProtoCodec)(nil), "test.HashProtoCodec")
}

func init() { proto.RegisterFile("proto_codec.proto", fileDescriptor_55a7f4844f88f049) }

var fileDescriptor_55a7f4844f88f049 = []byte{
	// 326 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x90, 0xc1, 0x4a, 0xc3, 0x30,
	0x18, 0xc7, 0xc9, 0xd6, 0xcd, 0x2d, 0x63, 0xa2, 0x45, 0x25, 0x4c, 0xa4, 0xc1, 0x53, 0x2e, 0xeb,
	0x60, 0x2b, 0x15, 0x86, 0xa7, 0x09, 0xa2, 0x37, 0xa9, 0x78, 0x1e, 0x6d, 0x97, 0xb5, 0x85, 0x6e,
	0x9f, 0x34, 0x29, 0xe8, 0xdb, 0x89, 0x8f, 0xe0, 0xd1, 0x43, 0x9f, 0x45, 0x92, 0x48, 0xdd, 0xba,
	0x47, 0xf0, 0xd4, 0x2f, 0xff, 0xef, 0xf7, 0x0b, 0xcd, 0x1f, 0x9f, 0xbe, 0x16, 0x20, 0x61, 0x19,
	0xc3, 0x8a, 0xc7, 0xae, 0x9e, 0x6d, 0x4b, 0x72, 0x21, 0x47, 0x37, 0x49, 0x26, 0xd3, 0x32, 0x72,
	0x63, 0xd8, 0x4c, 0x92, 0x30, 0x0f, 0xdf, 0xde, 0x21, 0xe2, 0x13, 0x4d, 0xc4, 0xe3, 0x84, 0x6f,
	0xc7, 0x05, 0x5f, 0x65, 0xc2, 0x04, 0x13, 0x3d, 0x1b, 0x7d, 0x34, 0xde, 0x15, 0x21, 0x01, 0x83,
	0x44, 0xe5, 0x5a, 0x9f, 0x0c, 0xaf, 0x26, 0x83, 0x5f, 0x7f, 0xb6, 0xf0, 0xc9, 0xb3, 0x2c, 0xb2,
	0x6d, 0xf2, 0xa4, 0xce, 0x77, 0xea, 0x47, 0x6c, 0x07, 0x0f, 0x04, 0x6c, 0xf8, 0x52, 0xe8, 0x05,
	0x41, 0x14, 0xb1, 0x7e, 0x80, 0x55, 0x64, 0x50, 0xfb, 0x12, 0xf7, 0x35, 0x10, 0x01, 0xe4, 0xa4,
	0x45, 0x11, 0xeb, 0x05, 0x3d, 0x15, 0x2c, 0x00, 0x72, 0xfb, 0x0a, 0x6b, 0x74, 0x99, 0x6d, 0xe5,
	0x6c, 0x4a, 0xda, 0x14, 0xb1, 0x4e, 0xa0, 0xf1, 0x47, 0x15, 0xd4, 0x97, 0x97, 0x66, 0x6f, 0x51,
	0xc4, 0x86, 0xe6, 0xf2, 0x17, 0x9d, 0xec, 0xfa, 0xbe, 0x47, 0x3a, 0x14, 0xb1, 0x76, 0xed, 0xfb,
	0xde, 0x9e, 0xef, 0x7b, 0xa4, 0x4b, 0x11, 0xb3, 0xfe, 0x7c, 0xdf, 0xab, 0xfd, 0x75, 0x0e, 0xa1,
	0x24, 0x47, 0x14, 0xb1, 0x96, 0xf1, 0xef, 0x55, 0x60, 0x2f, 0x0e, 0x1f, 0x4c, 0x7a, 0x14, 0xb1,
	0xc1, 0xf4, 0xc2, 0x55, 0xd5, 0xbb, 0xcd, 0x6d, 0x70, 0xc0, 0xcf, 0x87, 0x1f, 0x95, 0x83, 0xbe,
	0x2b, 0xa7, 0x53, 0x97, 0x78, 0xfc, 0x10, 0x8a, 0xf4, 0xbf, 0x54, 0x78, 0xdb, 0x7c, 0xee, 0x6f,
	0x81, 0x67, 0xa6, 0xc0, 0xfd, 0x5d, 0xd0, 0x60, 0xe7, 0xe7, 0xaa, 0xbc, 0xaf, 0xca, 0xb1, 0xd2,
	0x50, 0xa4, 0x75, 0x89, 0x51, 0x57, 0x7f, 0x66, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb7, 0x1f,
	0x50, 0xf8, 0x13, 0x03, 0x00, 0x00,
}
