// Code generated by protoc-gen-go. DO NOT EDIT.
// source: string_type.proto

package test

import (
	fmt "fmt"
	_ "github.com/galaxyobe/protoc-gen-redis/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StringStorageType_Enum int32

const (
	StringStorageType_E1 StringStorageType_Enum = 0
	StringStorageType_E2 StringStorageType_Enum = 1
)

var StringStorageType_Enum_name = map[int32]string{
	0: "E1",
	1: "E2",
}

var StringStorageType_Enum_value = map[string]int32{
	"E1": 0,
	"E2": 1,
}

func (x StringStorageType_Enum) String() string {
	return proto.EnumName(StringStorageType_Enum_name, int32(x))
}

func (StringStorageType_Enum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_55f9a8064f432806, []int{0, 0}
}

type StringStorageType struct {
	SomeString           string                 `protobuf:"bytes,1,opt,name=some_string,json=someString,proto3" json:"some_string,omitempty"`
	SomeBool             bool                   `protobuf:"varint,2,opt,name=some_bool,json=someBool,proto3" json:"some_bool,omitempty"`
	SomeInt32            int32                  `protobuf:"varint,3,opt,name=some_int32,json=someInt32,proto3" json:"some_int32,omitempty"`
	SomeUint32           uint32                 `protobuf:"varint,4,opt,name=some_uint32,json=someUint32,proto3" json:"some_uint32,omitempty"`
	SomeInt64            int64                  `protobuf:"varint,5,opt,name=some_int64,json=someInt64,proto3" json:"some_int64,omitempty"`
	SomeUint64           uint64                 `protobuf:"varint,6,opt,name=some_uint64,json=someUint64,proto3" json:"some_uint64,omitempty"`
	SomeFloat            float32                `protobuf:"fixed32,7,opt,name=some_float,json=someFloat,proto3" json:"some_float,omitempty"`
	SomeEnum             StringStorageType_Enum `protobuf:"varint,8,opt,name=some_enum,json=someEnum,proto3,enum=test.StringStorageType_Enum" json:"some_enum,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *StringStorageType) Reset()         { *m = StringStorageType{} }
func (m *StringStorageType) String() string { return proto.CompactTextString(m) }
func (*StringStorageType) ProtoMessage()    {}
func (*StringStorageType) Descriptor() ([]byte, []int) {
	return fileDescriptor_55f9a8064f432806, []int{0}
}

func (m *StringStorageType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringStorageType.Unmarshal(m, b)
}
func (m *StringStorageType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringStorageType.Marshal(b, m, deterministic)
}
func (m *StringStorageType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringStorageType.Merge(m, src)
}
func (m *StringStorageType) XXX_Size() int {
	return xxx_messageInfo_StringStorageType.Size(m)
}
func (m *StringStorageType) XXX_DiscardUnknown() {
	xxx_messageInfo_StringStorageType.DiscardUnknown(m)
}

var xxx_messageInfo_StringStorageType proto.InternalMessageInfo

func (m *StringStorageType) GetSomeString() string {
	if m != nil {
		return m.SomeString
	}
	return ""
}

func (m *StringStorageType) GetSomeBool() bool {
	if m != nil {
		return m.SomeBool
	}
	return false
}

func (m *StringStorageType) GetSomeInt32() int32 {
	if m != nil {
		return m.SomeInt32
	}
	return 0
}

func (m *StringStorageType) GetSomeUint32() uint32 {
	if m != nil {
		return m.SomeUint32
	}
	return 0
}

func (m *StringStorageType) GetSomeInt64() int64 {
	if m != nil {
		return m.SomeInt64
	}
	return 0
}

func (m *StringStorageType) GetSomeUint64() uint64 {
	if m != nil {
		return m.SomeUint64
	}
	return 0
}

func (m *StringStorageType) GetSomeFloat() float32 {
	if m != nil {
		return m.SomeFloat
	}
	return 0
}

func (m *StringStorageType) GetSomeEnum() StringStorageType_Enum {
	if m != nil {
		return m.SomeEnum
	}
	return StringStorageType_E1
}

type StringStorageType2 struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringStorageType2) Reset()         { *m = StringStorageType2{} }
func (m *StringStorageType2) String() string { return proto.CompactTextString(m) }
func (*StringStorageType2) ProtoMessage()    {}
func (*StringStorageType2) Descriptor() ([]byte, []int) {
	return fileDescriptor_55f9a8064f432806, []int{1}
}

func (m *StringStorageType2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringStorageType2.Unmarshal(m, b)
}
func (m *StringStorageType2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringStorageType2.Marshal(b, m, deterministic)
}
func (m *StringStorageType2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringStorageType2.Merge(m, src)
}
func (m *StringStorageType2) XXX_Size() int {
	return xxx_messageInfo_StringStorageType2.Size(m)
}
func (m *StringStorageType2) XXX_DiscardUnknown() {
	xxx_messageInfo_StringStorageType2.DiscardUnknown(m)
}

var xxx_messageInfo_StringStorageType2 proto.InternalMessageInfo

func (m *StringStorageType2) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

func init() {
	proto.RegisterEnum("test.StringStorageType_Enum", StringStorageType_Enum_name, StringStorageType_Enum_value)
	proto.RegisterType((*StringStorageType)(nil), "test.StringStorageType")
	proto.RegisterType((*StringStorageType2)(nil), "test.StringStorageType2")
}

func init() { proto.RegisterFile("string_type.proto", fileDescriptor_55f9a8064f432806) }

var fileDescriptor_55f9a8064f432806 = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0x41, 0x4f, 0xc2, 0x30,
	0x14, 0xc7, 0xed, 0x18, 0x13, 0x8a, 0x12, 0xe8, 0xc1, 0x34, 0xa8, 0xa1, 0x72, 0xea, 0x85, 0x11,
	0xc7, 0x32, 0x23, 0x89, 0x17, 0x13, 0x4c, 0xbc, 0x0e, 0x3d, 0x93, 0x0d, 0x4b, 0x5d, 0xb2, 0xad,
	0x64, 0xeb, 0x12, 0xf9, 0x76, 0x7e, 0x06, 0xbd, 0xf3, 0x59, 0x4c, 0x5b, 0x9c, 0x18, 0x4e, 0xef,
	0xed, 0xbf, 0xff, 0xef, 0xe5, 0xbd, 0x7f, 0x61, 0xbf, 0x94, 0x45, 0x92, 0xf3, 0xa5, 0xdc, 0x6e,
	0x98, 0xbb, 0x29, 0x84, 0x14, 0xc8, 0x96, 0xac, 0x94, 0x83, 0x3b, 0x9e, 0xc8, 0xf7, 0x2a, 0x76,
	0x57, 0x22, 0x9b, 0xf0, 0x28, 0x8d, 0x3e, 0xb6, 0x22, 0x66, 0x13, 0xed, 0x58, 0x8d, 0x39, 0xcb,
	0xc7, 0x05, 0x7b, 0x4b, 0x4a, 0x23, 0x4c, 0x74, 0x6f, 0xf0, 0xc1, 0xf8, 0x10, 0x14, 0x5c, 0x18,
	0x4b, 0x5c, 0xad, 0xf5, 0x97, 0xf1, 0xab, 0xce, 0xd8, 0x47, 0xdf, 0x16, 0xec, 0x2f, 0xf4, 0x0e,
	0x0b, 0x29, 0x8a, 0x88, 0xb3, 0x97, 0xed, 0x86, 0xa1, 0x21, 0xec, 0x94, 0x22, 0x63, 0x4b, 0xb3,
	0x1d, 0x06, 0x04, 0xd0, 0x76, 0x08, 0x95, 0x64, 0xbc, 0xe8, 0x12, 0xb6, 0xb5, 0x21, 0x16, 0x22,
	0xc5, 0x16, 0x01, 0xb4, 0x15, 0xb6, 0x94, 0xf0, 0x28, 0x44, 0x8a, 0xae, 0xa1, 0xb6, 0x2e, 0x93,
	0x5c, 0x4e, 0x3d, 0xdc, 0x20, 0x80, 0x36, 0x43, 0x6d, 0x7f, 0x56, 0x42, 0x3d, 0xbc, 0x32, 0xff,
	0x6d, 0x02, 0xe8, 0xb9, 0x19, 0xfe, 0xaa, 0x95, 0x43, 0x3e, 0xf0, 0x71, 0x93, 0x00, 0xda, 0xa8,
	0xf9, 0xc0, 0xff, 0xc7, 0x07, 0x3e, 0x76, 0x08, 0xa0, 0xf6, 0x1f, 0x1f, 0xf8, 0x35, 0xbf, 0x4e,
	0x45, 0x24, 0xf1, 0x29, 0x01, 0xd4, 0x32, 0xfc, 0x93, 0x12, 0xd0, 0xfd, 0x7e, 0x77, 0x96, 0x57,
	0x19, 0x6e, 0x11, 0x40, 0xbb, 0xde, 0x95, 0xab, 0x42, 0x77, 0x8f, 0x82, 0x70, 0xe7, 0x79, 0x95,
	0x99, 0xcb, 0x54, 0x37, 0xba, 0x80, 0xb6, 0xaa, 0xc8, 0x81, 0xd6, 0xfc, 0xb6, 0x77, 0xa2, 0xab,
	0xd7, 0x03, 0xb3, 0xee, 0xe7, 0x6e, 0x08, 0xbe, 0x76, 0x43, 0xc7, 0x04, 0x36, 0x7a, 0x80, 0xe8,
	0x68, 0x96, 0x87, 0x6e, 0xe0, 0xd9, 0xef, 0x5d, 0x8c, 0xb3, 0x42, 0xc7, 0xda, 0x0c, 0x3b, 0xfb,
	0xcb, 0x94, 0x34, 0xb3, 0xd5, 0xa0, 0xd8, 0xd1, 0x6f, 0x33, 0xfd, 0x09, 0x00, 0x00, 0xff, 0xff,
	0xce, 0xbb, 0x80, 0x67, 0x1e, 0x02, 0x00, 0x00,
}
