// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: string_type.proto

package test

import context "context"
import github_com_gomodule_redigo_redis "github.com/gomodule/redigo/redis"
import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/galaxyobe/protoc-gen-redis/proto"
import _ "github.com/gogo/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// new StringStorageType redis controller with redis pool
func (m *StringStorageType) RedisController(pool *github_com_gomodule_redigo_redis.Pool) *StringStorageTypeRedisController {
	return &StringStorageTypeRedisController{
		pool: pool,
		m:    m,
	}
}

// StringStorageType redis controller
type StringStorageTypeRedisController struct {
	pool *github_com_gomodule_redigo_redis.Pool
	m    *StringStorageType
}

// new StringStorageType redis controller with redis pool
func NewStringStorageTypeRedisController(pool *github_com_gomodule_redigo_redis.Pool) *StringStorageTypeRedisController {
	return &StringStorageTypeRedisController{pool: pool, m: new(StringStorageType)}
}

// get StringStorageType
func (r *StringStorageTypeRedisController) StringStorageType() *StringStorageType {
	return r.m
}

// set StringStorageType
func (r *StringStorageTypeRedisController) SetStringStorageType(m *StringStorageType) {
	r.m = m
}

// store StringStorageType to redis string with context and key
func (r *StringStorageTypeRedisController) Store(ctx context.Context, key string) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// marshal StringStorageType to []byte
	data, err := proto.Marshal(r.m)
	if err != nil {
		return err
	}

	// use redis string store StringStorageType data
	_, err = conn.Do("SET", key, data)

	return err
}

// store StringStorageType to redis string with context, key and ttl expire second
func (r *StringStorageTypeRedisController) StoreWithTTL(ctx context.Context, key string, ttl uint64) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// marshal StringStorageType to []byte
	data, err := proto.Marshal(r.m)
	if err != nil {
		return err
	}

	// use redis string store StringStorageType data with expire second
	_, err = conn.Do("SETEX", key, ttl, data)

	return err
}

// load StringStorageType from redis string with context and key
func (r *StringStorageTypeRedisController) Load(ctx context.Context, key string) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// load data from redis string
	data, err := github_com_gomodule_redigo_redis.Bytes(conn.Do("GET", key))
	if err != nil {
		return err
	}

	// unmarshal data to StringStorageType
	return proto.Unmarshal(data, r.m)
}

// new StringStorageTyp2 redis controller with redis pool
func (m *StringStorageTyp2) RedisController(pool *github_com_gomodule_redigo_redis.Pool) *StringStorageTyp2RedisController {
	return &StringStorageTyp2RedisController{
		pool: pool,
		m:    m,
	}
}

// StringStorageTyp2 redis controller
type StringStorageTyp2RedisController struct {
	pool *github_com_gomodule_redigo_redis.Pool
	m    *StringStorageTyp2
}

// new StringStorageTyp2 redis controller with redis pool
func NewStringStorageTyp2RedisController(pool *github_com_gomodule_redigo_redis.Pool) *StringStorageTyp2RedisController {
	return &StringStorageTyp2RedisController{pool: pool, m: new(StringStorageTyp2)}
}

// get StringStorageTyp2
func (r *StringStorageTyp2RedisController) StringStorageTyp2() *StringStorageTyp2 {
	return r.m
}

// set StringStorageTyp2
func (r *StringStorageTyp2RedisController) SetStringStorageTyp2(m *StringStorageTyp2) {
	r.m = m
}

// store StringStorageTyp2 to redis string with context and key
func (r *StringStorageTyp2RedisController) Store(ctx context.Context, key string) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// marshal StringStorageTyp2 to []byte
	data, err := proto.Marshal(r.m)
	if err != nil {
		return err
	}

	// use redis string store StringStorageTyp2 data
	_, err = conn.Do("SET", key, data)

	return err
}

// store StringStorageTyp2 to redis string with context, key and ttl expire second
func (r *StringStorageTyp2RedisController) StoreWithTTL(ctx context.Context, key string, ttl uint64) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// marshal StringStorageTyp2 to []byte
	data, err := proto.Marshal(r.m)
	if err != nil {
		return err
	}

	// use redis string store StringStorageTyp2 data with expire second
	_, err = conn.Do("SETEX", key, ttl, data)

	return err
}

// load StringStorageTyp2 from redis string with context and key
func (r *StringStorageTyp2RedisController) Load(ctx context.Context, key string) error {
	// redis conn
	conn := r.pool.Get()
	defer conn.Close()

	// load data from redis string
	data, err := github_com_gomodule_redigo_redis.Bytes(conn.Do("GET", key))
	if err != nil {
		return err
	}

	// unmarshal data to StringStorageType
	return proto.Unmarshal(data, r.m)
}
