// Code generated by protoc-gen-go. DO NOT EDIT.
// source: string_type.proto

package test

import (
	fmt "fmt"
	_ "github.com/galaxyobe/protoc-gen-redis/proto"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type StringStorageType struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringStorageType) Reset()         { *m = StringStorageType{} }
func (m *StringStorageType) String() string { return proto.CompactTextString(m) }
func (*StringStorageType) ProtoMessage()    {}
func (*StringStorageType) Descriptor() ([]byte, []int) {
	return fileDescriptor_55f9a8064f432806, []int{0}
}

func (m *StringStorageType) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringStorageType.Unmarshal(m, b)
}
func (m *StringStorageType) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringStorageType.Marshal(b, m, deterministic)
}
func (m *StringStorageType) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringStorageType.Merge(m, src)
}
func (m *StringStorageType) XXX_Size() int {
	return xxx_messageInfo_StringStorageType.Size(m)
}
func (m *StringStorageType) XXX_DiscardUnknown() {
	xxx_messageInfo_StringStorageType.DiscardUnknown(m)
}

var xxx_messageInfo_StringStorageType proto.InternalMessageInfo

func (m *StringStorageType) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

type StringStorageTyp2 struct {
	SomeInteger          int32    `protobuf:"varint,1,opt,name=some_integer,json=someInteger,proto3" json:"some_integer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StringStorageTyp2) Reset()         { *m = StringStorageTyp2{} }
func (m *StringStorageTyp2) String() string { return proto.CompactTextString(m) }
func (*StringStorageTyp2) ProtoMessage()    {}
func (*StringStorageTyp2) Descriptor() ([]byte, []int) {
	return fileDescriptor_55f9a8064f432806, []int{1}
}

func (m *StringStorageTyp2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringStorageTyp2.Unmarshal(m, b)
}
func (m *StringStorageTyp2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringStorageTyp2.Marshal(b, m, deterministic)
}
func (m *StringStorageTyp2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringStorageTyp2.Merge(m, src)
}
func (m *StringStorageTyp2) XXX_Size() int {
	return xxx_messageInfo_StringStorageTyp2.Size(m)
}
func (m *StringStorageTyp2) XXX_DiscardUnknown() {
	xxx_messageInfo_StringStorageTyp2.DiscardUnknown(m)
}

var xxx_messageInfo_StringStorageTyp2 proto.InternalMessageInfo

func (m *StringStorageTyp2) GetSomeInteger() int32 {
	if m != nil {
		return m.SomeInteger
	}
	return 0
}

func init() {
	proto.RegisterType((*StringStorageType)(nil), "test.StringStorageType")
	proto.RegisterType((*StringStorageTyp2)(nil), "test.StringStorageTyp2")
}

func init() { proto.RegisterFile("string_type.proto", fileDescriptor_55f9a8064f432806) }

var fileDescriptor_55f9a8064f432806 = []byte{
	// 191 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2c, 0x2e, 0x29, 0xca,
	0xcc, 0x4b, 0x8f, 0x2f, 0xa9, 0x2c, 0x48, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x29,
	0x49, 0x2d, 0x2e, 0x91, 0x32, 0x4f, 0xcf, 0x2c, 0xc9, 0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5,
	0x4f, 0x4f, 0xcc, 0x49, 0xac, 0xa8, 0xcc, 0x4f, 0x4a, 0xd5, 0x07, 0xab, 0x48, 0xd6, 0x4d, 0x4f,
	0xcd, 0xd3, 0x2d, 0x4a, 0x4d, 0xc9, 0x2c, 0x86, 0x08, 0xe8, 0x83, 0xd9, 0x10, 0xed, 0x52, 0xba,
	0xc8, 0x1a, 0xf3, 0xd3, 0xf3, 0x21, 0x4a, 0x92, 0x4a, 0xd3, 0xc0, 0x3c, 0x88, 0x7a, 0x10, 0x0b,
	0xa2, 0x5c, 0xc9, 0x8d, 0x4b, 0x30, 0x18, 0xec, 0x84, 0xe0, 0x92, 0xfc, 0xa2, 0xc4, 0xf4, 0xd4,
	0x90, 0xca, 0x82, 0x54, 0x21, 0x45, 0x2e, 0x9e, 0xe2, 0xfc, 0xdc, 0xd4, 0xf8, 0xcc, 0xbc, 0x92,
	0xd4, 0xf4, 0xd4, 0x22, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0x6e, 0x90, 0x98, 0x27, 0x44,
	0xc8, 0x8a, 0xef, 0xc0, 0x3d, 0x79, 0xc6, 0x4b, 0xf7, 0xe4, 0xd9, 0x20, 0x1e, 0x50, 0x72, 0xc0,
	0x34, 0xc7, 0x88, 0x18, 0x73, 0x38, 0x40, 0xe6, 0x9c, 0xb8, 0x27, 0xcf, 0x90, 0xc4, 0x06, 0x76,
	0x90, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x12, 0x8c, 0xf7, 0x70, 0x13, 0x01, 0x00, 0x00,
}
